OBJS1 = agenda.obj,analysis.obj,argacces.obj,bload.obj,-
	bmathfun.obj,bsave.obj,classcom.obj,classexm.obj,-
	classfun.obj,classinf.obj,classini.obj,classpsr.obj,-
	clsltpsr.obj,commline.obj,conscomp.obj,constrct.obj,- 
	constrnt.obj,crstrtgy.obj,cstrcbin.obj,cstrccom.obj,- 
	cstrcpsr.obj,cstrnbin.obj,cstrnchk.obj,cstrncmp.obj,-
	cstrnops.obj,cstrnpsr.obj,cstrnutl.obj,default.obj,-
	defins.obj,developr.obj,dffctbin.obj,dffctbsc.obj,- 
	dffctcmp.obj,dffctdef.obj,dffctpsr.obj,dffnxbin.obj,-
	dffnxcmp.obj,dffnxexe.obj,dffnxfun.obj,dffnxpsr.obj,-
	dfinsbin.obj,dfinscmp.obj,drive.obj,edbasic.obj,-
	edmain.obj,edmisc.obj,edstruct.obj,edterm.obj,emathfun.obj,- 
	engine.obj,evaluatn.obj,expressn.obj,exprnbin.obj,-
	exprnops.obj,exprnpsr.obj,extnfunc.obj,factbin.obj

OBJS2 =	factbld.obj,factcmp.obj,factcom.obj,factfun.obj,-
	factgen.obj,facthsh.obj,factlhs.obj,factmch.obj,-
	factmngr.obj,factprt.obj,factrete.obj,factrhs.obj,-
	filecom.obj,filertr.obj,generate.obj,genrcbin.obj,-
	genrccmp.obj,genrccom.obj,genrcexe.obj,genrcfun.obj,-
	genrcpsr.obj,globlbin.obj,globlbsc.obj,globlcmp.obj,-
	globlcom.obj,globldef.obj,globlpsr.obj,immthpsr.obj,-
	incrrset.obj,inherpsr.obj,inscom.obj,insfile.obj,-
	insfun.obj,insmngr.obj,insmoddp.obj,insmult.obj,- 
	inspsr.obj,insquery.obj,insqypsr.obj,iofun.obj,-
	lgcldpnd.obj,memalloc.obj,miscfun.obj,-
	modulbin.obj,modulbsc.obj,modulcmp.obj,moduldef.obj

OBJS3 =	modulpsr.obj,modulutl.obj,msgcom.obj,msgfun.obj,-
	msgpass.obj,msgpsr.obj,multifld.obj,multifun.obj,-
	objbin.obj,objcmp.obj,objrtbin.obj,objrtbld.obj,-
	objrtcmp.obj,objrtfnx.obj,objrtgen.obj,objrtmch.obj,-
	parsefun.obj,pattern.obj,pprint.obj,prccode.obj,-
	prcdrfun.obj,prcdrpsr.obj,prdctfun.obj,prntutil.obj,-
 	proflfun.obj,reorder.obj,reteutil.obj,retract.obj,-
	router.obj,rulebin.obj,rulebld.obj,rulebsc.obj

OBJS4 =	rulecmp.obj,rulecom.obj,rulecstr.obj,ruledef.obj,-
 	ruledlt.obj,rulelhs.obj,rulepsr.obj,scanner.obj,-
	sortfun.obj,strngfun.obj,strngrtr.obj,symblbin.obj,-
	symblcmp.obj,symbol.obj,sysdep.obj,textpro.obj,-
 	tmpltbin.obj,tmpltbsc.obj,tmpltcmp.obj,tmpltdef.obj,-
	tmpltfun.obj,tmpltlhs.obj,tmpltpsr.obj,tmpltrhs.obj,-
	tmpltutl.obj,userdata.obj,utility.obj,watch.obj 

FUZZY_OBJS = fuzzycom.obj,fuzzydef.obj,fuzzylhs.obj,fuzzymod.obj,-
	fuzzypsr.obj,fuzzyrhs.obj,fuzzyutl.obj,cfdef.obj


.c.obj :
	CC/NOWARNINGS/OBJECT=$(MMS$TARGET) $(MMS$SOURCE)


fzclips.exe : clipslib.olb,main.obj
	link/exec=fzclips.exe main.obj,clipslib.olb/lib,sys$share:decc$crtl/lib

clipslib.olb : $(OBJS1),$(OBJS2),$(OBJS3),$(OBJS4)
	library/create clipslib $(OBJS1)
	library/insert/replace clipslib $(OBJS2)
	library/insert/replace clipslib $(OBJS3)
	library/insert/replace clipslib $(OBJS4)
	library/insert/replace clipslib $(FUZZY_OBJS)

# DO NOT DELETE

agenda.obj : setup.h,argacces.h,symbol.h,fuzzyval.h,tmpltdef.h,expressn.h
agenda.obj : exprnops.h,evaluatn.h,constant.h,userdata.h,constrct.h,moduldef.h
agenda.obj : scanner.h,pprint.h,constrnt.h,factbld.h,pattern.h,match.h,network.h
agenda.obj : ruledef.h,cstrccom.h,agenda.h,reorder.h,factmngr.h,multifld.h
agenda.obj : fuzzylv.h,dffnxfun.h,extnfunc.h,crstrtgy.h,engine.h,memalloc.h
agenda.obj : modulutl.h,reteutil.h,retract.h,router.h,prntutil.h,rulebsc.h
agenda.obj : strngrtr.h,sysdep.h,watch.h,cfdef.h
analysis.obj : setup.h,constant.h,symbol.h,fuzzyval.h,tmpltdef.h,expressn.h
analysis.obj : exprnops.h,evaluatn.h,userdata.h,constrct.h,moduldef.h,scanner.h
analysis.obj : pprint.h,constrnt.h,factbld.h,pattern.h,match.h,network.h
analysis.obj : ruledef.h,cstrccom.h,agenda.h,reorder.h,factmngr.h,multifld.h
analysis.obj : fuzzylv.h,dffnxfun.h,extnfunc.h,memalloc.h,exprnpsr.h,generate.h
analysis.obj : router.h,prntutil.h,cstrnchk.h,cstrnutl.h,cstrnops.h,rulecstr.h
analysis.obj : modulutl.h,analysis.h,globldef.h
argacces.obj : setup.h,extnfunc.h,userdata.h,router.h,prntutil.h,cstrnchk.h
argacces.obj : insfun.h,evaluatn.h,constant.h,moduldef.h,object.h,constrct.h
argacces.obj : scanner.h,pprint.h,constrnt.h,expressn.h,exprnops.h,multifld.h
argacces.obj : symbol.h,fuzzyval.h,tmpltdef.h,factbld.h,pattern.h,match.h
argacces.obj : network.h,ruledef.h,cstrccom.h,agenda.h,reorder.h,factmngr.h
argacces.obj : fuzzylv.h,dffnxfun.h,argacces.h
bload.obj : setup.h,memalloc.h,exprnpsr.h,argacces.h,symbol.h,fuzzyval.h
bload.obj : tmpltdef.h,expressn.h,exprnops.h,evaluatn.h,constant.h,userdata.h
bload.obj : constrct.h,moduldef.h,scanner.h,pprint.h,constrnt.h,factbld.h
bload.obj : pattern.h,match.h,network.h,ruledef.h,cstrccom.h,agenda.h,reorder.h
bload.obj : factmngr.h,multifld.h,fuzzylv.h,dffnxfun.h,extnfunc.h,router.h
bload.obj : prntutil.h,bsave.h,cstrnbin.h,utility.h,bload.h,exprnbin.h,sysdep.h
bload.obj : symblbin.h
bmathfun.obj : setup.h,exprnpsr.h,argacces.h,symbol.h,fuzzyval.h,tmpltdef.h
bmathfun.obj : expressn.h,exprnops.h,evaluatn.h,constant.h,userdata.h,constrct.h
bmathfun.obj : moduldef.h,scanner.h,pprint.h,constrnt.h,factbld.h,pattern.h
bmathfun.obj : match.h,network.h,ruledef.h,cstrccom.h,agenda.h,reorder.h
bmathfun.obj : factmngr.h,multifld.h,fuzzylv.h,dffnxfun.h,extnfunc.h,router.h
bmathfun.obj : prntutil.h,bmathfun.h
bsave.obj : setup.h,memalloc.h,exprnpsr.h,argacces.h,symbol.h,fuzzyval.h
bsave.obj : tmpltdef.h,expressn.h,exprnops.h,evaluatn.h,constant.h,userdata.h
bsave.obj : constrct.h,moduldef.h,scanner.h,pprint.h,constrnt.h,factbld.h
bsave.obj : pattern.h,match.h,network.h,ruledef.h,cstrccom.h,agenda.h,reorder.h
bsave.obj : factmngr.h,multifld.h,fuzzylv.h,dffnxfun.h,extnfunc.h,router.h
bsave.obj : prntutil.h,cstrnbin.h,symblbin.h,bload.h,exprnbin.h,sysdep.h,bsave.h
cfdef.obj : setup.h,symbol.h,fuzzyval.h,tmpltdef.h,expressn.h,exprnops.h
cfdef.obj : evaluatn.h,constant.h,userdata.h,constrct.h,moduldef.h,scanner.h
cfdef.obj : pprint.h,constrnt.h,factbld.h,pattern.h,match.h,network.h,ruledef.h
cfdef.obj : cstrccom.h,agenda.h,reorder.h,factmngr.h,multifld.h,fuzzylv.h
cfdef.obj : dffnxfun.h,extnfunc.h,cfdef.h,fuzzyutl.h,fuzzypsr.h,fuzzyrhs.h
cfdef.obj : fuzzymod.h,prntutil.h,argacces.h,engine.h,router.h,exprnpsr.h
classcom.obj : setup.h,bload.h,exprnbin.h,sysdep.h,symblbin.h,argacces.h
classcom.obj : symbol.h,fuzzyval.h,tmpltdef.h,expressn.h,exprnops.h,evaluatn.h
classcom.obj : constant.h,userdata.h,constrct.h,moduldef.h,scanner.h,pprint.h
classcom.obj : constrnt.h,factbld.h,pattern.h,match.h,network.h,ruledef.h
classcom.obj : cstrccom.h,agenda.h,reorder.h,factmngr.h,multifld.h,fuzzylv.h
classcom.obj : dffnxfun.h,extnfunc.h,classfun.h,object.h,classini.h,modulutl.h
classcom.obj : msgcom.h,router.h,prntutil.h,classcom.h
classexm.obj : setup.h,argacces.h,symbol.h,fuzzyval.h,tmpltdef.h,expressn.h
classexm.obj : exprnops.h,evaluatn.h,constant.h,userdata.h,constrct.h,moduldef.h
classexm.obj : scanner.h,pprint.h,constrnt.h,factbld.h,pattern.h,match.h
classexm.obj : network.h,ruledef.h,cstrccom.h,agenda.h,reorder.h,factmngr.h
classexm.obj : multifld.h,fuzzylv.h,dffnxfun.h,extnfunc.h,classcom.h,classfun.h
classexm.obj : object.h,classini.h,memalloc.h,insfun.h,msgcom.h,msgfun.h
classexm.obj : msgpass.h,router.h,prntutil.h,strngrtr.h,classexm.h
classfun.obj : setup.h,bload.h,exprnbin.h,sysdep.h,symblbin.h,classcom.h
classfun.obj : classini.h,memalloc.h,constant.h,constrct.h,moduldef.h,userdata.h
classfun.obj : scanner.h,pprint.h,cstrccom.h,cstrcpsr.h,evaluatn.h,inscom.h
classfun.obj : object.h,constrnt.h,expressn.h,exprnops.h,multifld.h,symbol.h
classfun.obj : fuzzyval.h,tmpltdef.h,factbld.h,pattern.h,match.h,network.h
classfun.obj : ruledef.h,agenda.h,reorder.h,factmngr.h,fuzzylv.h,dffnxfun.h
classfun.obj : extnfunc.h,insfun.h,insmngr.h,modulutl.h,msgfun.h,msgpass.h
classfun.obj : router.h,prntutil.h,utility.h,classfun.h
classinf.obj : setup.h,argacces.h,symbol.h,fuzzyval.h,tmpltdef.h,expressn.h
classinf.obj : exprnops.h,evaluatn.h,constant.h,userdata.h,constrct.h,moduldef.h
classinf.obj : scanner.h,pprint.h,constrnt.h,factbld.h,pattern.h,match.h
classinf.obj : network.h,ruledef.h,cstrccom.h,agenda.h,reorder.h,factmngr.h
classinf.obj : multifld.h,fuzzylv.h,dffnxfun.h,extnfunc.h,classcom.h,classexm.h
classinf.obj : classfun.h,object.h,classini.h,memalloc.h,insfun.h,msgfun.h
classinf.obj : msgpass.h,prntutil.h,classinf.h
classini.obj : setup.h,classcom.h,classexm.h,classfun.h,object.h,constrct.h
classini.obj : moduldef.h,userdata.h,scanner.h,pprint.h,constrnt.h,expressn.h
classini.obj : exprnops.h,multifld.h,symbol.h,fuzzyval.h,tmpltdef.h,evaluatn.h
classini.obj : constant.h,factbld.h,pattern.h,match.h,network.h,ruledef.h
classini.obj : cstrccom.h,agenda.h,reorder.h,factmngr.h,fuzzylv.h,dffnxfun.h
classini.obj : extnfunc.h,classinf.h,classpsr.h,memalloc.h,cstrcpsr.h,inscom.h
classini.obj : modulpsr.h,modulutl.h,msgcom.h,watch.h,defins.h,insquery.h
classini.obj : objbin.h,objcmp.h,objrtbld.h,classini.h
classpsr.obj : setup.h,bload.h,exprnbin.h,sysdep.h,symblbin.h,classcom.h
classpsr.obj : classfun.h,object.h,constrct.h,moduldef.h,userdata.h,scanner.h
classpsr.obj : pprint.h,constrnt.h,expressn.h,exprnops.h,multifld.h,symbol.h
classpsr.obj : fuzzyval.h,tmpltdef.h,evaluatn.h,constant.h,factbld.h,pattern.h
classpsr.obj : match.h,network.h,ruledef.h,cstrccom.h,agenda.h,reorder.h
classpsr.obj : factmngr.h,fuzzylv.h,dffnxfun.h,extnfunc.h,memalloc.h,cstrcpsr.h
classpsr.obj : inherpsr.h,modulpsr.h,modulutl.h,msgpsr.h,clsltpsr.h,router.h
classpsr.obj : prntutil.h,classpsr.h
clsltpsr.obj : setup.h,classfun.h,object.h,constrct.h,moduldef.h,userdata.h
clsltpsr.obj : scanner.h,pprint.h,constrnt.h,expressn.h,exprnops.h,multifld.h
clsltpsr.obj : symbol.h,fuzzyval.h,tmpltdef.h,evaluatn.h,constant.h,factbld.h
clsltpsr.obj : pattern.h,match.h,network.h,ruledef.h,cstrccom.h,agenda.h
clsltpsr.obj : reorder.h,factmngr.h,fuzzylv.h,dffnxfun.h,extnfunc.h,memalloc.h
clsltpsr.obj : cstrnchk.h,cstrnpsr.h,cstrnutl.h,default.h,insfun.h,prntutil.h
clsltpsr.obj : router.h,clsltpsr.h
commline.obj : setup.h,constant.h,symbol.h,fuzzyval.h,tmpltdef.h,expressn.h
commline.obj : exprnops.h,evaluatn.h,userdata.h,constrct.h,moduldef.h,scanner.h
commline.obj : pprint.h,constrnt.h,factbld.h,pattern.h,match.h,network.h
commline.obj : ruledef.h,cstrccom.h,agenda.h,reorder.h,factmngr.h,multifld.h
commline.obj : fuzzylv.h,dffnxfun.h,extnfunc.h,memalloc.h,exprnpsr.h,argacces.h
commline.obj : router.h,prntutil.h,strngrtr.h,prcdrfun.h,prcdrpsr.h,utility.h
commline.obj : filecom.h,cstrcpsr.h,commline.h
conscomp.obj : setup.h,symbol.h,fuzzyval.h,tmpltdef.h,expressn.h,exprnops.h
conscomp.obj : evaluatn.h,constant.h,userdata.h,constrct.h,moduldef.h,scanner.h
conscomp.obj : pprint.h,constrnt.h,factbld.h,pattern.h,match.h,network.h
conscomp.obj : ruledef.h,cstrccom.h,agenda.h,reorder.h,factmngr.h,multifld.h
conscomp.obj : fuzzylv.h,dffnxfun.h,extnfunc.h,memalloc.h,exprnpsr.h,argacces.h
conscomp.obj : cstrncmp.h,router.h,prntutil.h,utility.h,modulcmp.h,dffnxcmp.h
conscomp.obj : tmpltcmp.h,globlcmp.h,genrccmp.h,genrcfun.h,object.h,objcmp.h
conscomp.obj : conscomp.h,symblcmp.h
constrct.obj : setup.h,constant.h,memalloc.h,router.h,prntutil.h,scanner.h
constrct.obj : pprint.h,watch.h,prcdrfun.h,prcdrpsr.h,argacces.h,symbol.h
constrct.obj : fuzzyval.h,tmpltdef.h,expressn.h,exprnops.h,evaluatn.h,userdata.h
constrct.obj : constrct.h,moduldef.h,constrnt.h,factbld.h,pattern.h,match.h
constrct.obj : network.h,ruledef.h,cstrccom.h,agenda.h,reorder.h,factmngr.h
constrct.obj : multifld.h,fuzzylv.h,dffnxfun.h,extnfunc.h,exprnpsr.h,utility.h
constrct.obj : commline.h
constrnt.obj : setup.h,constant.h,memalloc.h,router.h,prntutil.h,extnfunc.h
constrnt.obj : userdata.h,scanner.h,pprint.h,multifld.h,constrnt.h,argacces.h
constrnt.obj : symbol.h,fuzzyval.h,tmpltdef.h,expressn.h,exprnops.h,evaluatn.h
constrnt.obj : constrct.h,moduldef.h,factbld.h,pattern.h,match.h,network.h
constrnt.obj : ruledef.h,cstrccom.h,agenda.h,reorder.h,factmngr.h,fuzzylv.h
constrnt.obj : dffnxfun.h
crstrtgy.obj : setup.h,constant.h,pattern.h,match.h,network.h,ruledef.h
crstrtgy.obj : cstrccom.h,agenda.h,reorder.h,reteutil.h,argacces.h,symbol.h
crstrtgy.obj : fuzzyval.h,tmpltdef.h,expressn.h,exprnops.h,evaluatn.h,userdata.h
crstrtgy.obj : constrct.h,moduldef.h,scanner.h,pprint.h,constrnt.h,factbld.h
crstrtgy.obj : factmngr.h,multifld.h,fuzzylv.h,dffnxfun.h,extnfunc.h,crstrtgy.h
cstrcbin.obj : setup.h,bload.h,exprnbin.h,sysdep.h,symblbin.h,bsave.h,moduldef.h
cstrcbin.obj : cstrcbin.h,constrct.h,userdata.h,scanner.h,pprint.h
cstrccom.obj : setup.h,constant.h,memalloc.h,moduldef.h,argacces.h,symbol.h
cstrccom.obj : fuzzyval.h,tmpltdef.h,expressn.h,exprnops.h,evaluatn.h,userdata.h
cstrccom.obj : constrct.h,scanner.h,pprint.h,constrnt.h,factbld.h,pattern.h
cstrccom.obj : match.h,network.h,ruledef.h,cstrccom.h,agenda.h,reorder.h
cstrccom.obj : factmngr.h,multifld.h,fuzzylv.h,dffnxfun.h,extnfunc.h,modulutl.h
cstrccom.obj : router.h,prntutil.h,utility.h,commline.h,bload.h,exprnbin.h
cstrccom.obj : sysdep.h,symblbin.h,cstrcpsr.h
cstrcpsr.obj : setup.h,router.h,prntutil.h,watch.h,constrct.h,moduldef.h
cstrcpsr.obj : userdata.h,scanner.h,pprint.h,prcdrpsr.h,exprnpsr.h,modulutl.h
cstrcpsr.obj : modulpsr.h,utility.h,cstrcpsr.h,evaluatn.h,constant.h
cstrnbin.obj : setup.h,constant.h,memalloc.h,router.h,prntutil.h,bload.h
cstrnbin.obj : exprnbin.h,sysdep.h,symblbin.h,bsave.h,cstrnbin.h
cstrnchk.obj : setup.h,router.h,prntutil.h,multifld.h,extnfunc.h,userdata.h
cstrnchk.obj : cstrnutl.h,cstrnchk.h
cstrncmp.obj : setup.h,constant.h,memalloc.h,router.h,prntutil.h,conscomp.h
cstrncmp.obj : symblcmp.h,cstrncmp.h
cstrnops.obj : setup.h,constant.h,memalloc.h,router.h,prntutil.h,extnfunc.h
cstrnops.obj : userdata.h,scanner.h,pprint.h,multifld.h,constrnt.h,cstrnchk.h
cstrnops.obj : cstrnutl.h,cstrnops.h
cstrnpsr.obj : setup.h,constant.h,memalloc.h,router.h,prntutil.h,scanner.h
cstrnpsr.obj : pprint.h,cstrnutl.h,cstrnchk.h,cstrnpsr.h,tmpltdef.h,expressn.h
cstrnpsr.obj : exprnops.h,evaluatn.h,userdata.h,constrct.h,moduldef.h,constrnt.h
cstrnpsr.obj : factbld.h,pattern.h,match.h,network.h,ruledef.h,cstrccom.h
cstrnpsr.obj : agenda.h,reorder.h,factmngr.h,multifld.h,fuzzylv.h,dffnxfun.h
cstrnpsr.obj : extnfunc.h,modulutl.h
cstrnutl.obj : setup.h,constant.h,memalloc.h,router.h,prntutil.h,extnfunc.h
cstrnutl.obj : userdata.h,scanner.h,pprint.h,multifld.h,argacces.h,symbol.h
cstrnutl.obj : fuzzyval.h,tmpltdef.h,expressn.h,exprnops.h,evaluatn.h,constrct.h
cstrnutl.obj : moduldef.h,constrnt.h,factbld.h,pattern.h,match.h,network.h
cstrnutl.obj : ruledef.h,cstrccom.h,agenda.h,reorder.h,factmngr.h,fuzzylv.h
cstrnutl.obj : dffnxfun.h,cstrnutl.h
default.obj : setup.h,constant.h,tmpltdef.h,expressn.h,exprnops.h,evaluatn.h
default.obj : userdata.h,constrct.h,moduldef.h,scanner.h,pprint.h,constrnt.h
default.obj : factbld.h,pattern.h,match.h,network.h,ruledef.h,cstrccom.h
default.obj : agenda.h,reorder.h,factmngr.h,multifld.h,fuzzylv.h,dffnxfun.h
default.obj : extnfunc.h,cstrnchk.h,inscom.h,object.h,symbol.h,fuzzyval.h
default.obj : exprnpsr.h,router.h,prntutil.h,cstrnutl.h,default.h
defins.obj : setup.h,bload.h,exprnbin.h,sysdep.h,symblbin.h,dfinsbin.h
defins.obj : dfinscmp.h,argacces.h,symbol.h,fuzzyval.h,tmpltdef.h,expressn.h
defins.obj : exprnops.h,evaluatn.h,constant.h,userdata.h,constrct.h,moduldef.h
defins.obj : scanner.h,pprint.h,constrnt.h,factbld.h,pattern.h,match.h,network.h
defins.obj : ruledef.h,cstrccom.h,agenda.h,reorder.h,factmngr.h,multifld.h
defins.obj : fuzzylv.h,dffnxfun.h,extnfunc.h,classcom.h,classfun.h,object.h
defins.obj : memalloc.h,cstrcpsr.h,insfun.h,inspsr.h,modulpsr.h,router.h
defins.obj : prntutil.h,utility.h,defins.h
developr.obj : setup.h,router.h,prntutil.h,argacces.h,symbol.h,fuzzyval.h
developr.obj : tmpltdef.h,expressn.h,exprnops.h,evaluatn.h,constant.h,userdata.h
developr.obj : constrct.h,moduldef.h,scanner.h,pprint.h,constrnt.h,factbld.h
developr.obj : pattern.h,match.h,network.h,ruledef.h,cstrccom.h,agenda.h
developr.obj : reorder.h,factmngr.h,multifld.h,fuzzylv.h,dffnxfun.h,extnfunc.h
developr.obj : modulutl.h,facthsh.h,classcom.h,classfun.h,object.h,objrtmch.h
developr.obj : developr.h
dffctbin.obj : setup.h,memalloc.h,dffctdef.h,symbol.h,fuzzyval.h,tmpltdef.h
dffctbin.obj : expressn.h,exprnops.h,evaluatn.h,constant.h,userdata.h,constrct.h
dffctbin.obj : moduldef.h,scanner.h,pprint.h,constrnt.h,factbld.h,pattern.h
dffctbin.obj : match.h,network.h,ruledef.h,cstrccom.h,agenda.h,reorder.h
dffctbin.obj : factmngr.h,multifld.h,fuzzylv.h,dffnxfun.h,extnfunc.h,bload.h
dffctbin.obj : exprnbin.h,sysdep.h,symblbin.h,bsave.h,dffctbin.h,modulbin.h
dffctbin.obj : cstrcbin.h
dffctbsc.obj : setup.h,argacces.h,symbol.h,fuzzyval.h,tmpltdef.h,expressn.h
dffctbsc.obj : exprnops.h,evaluatn.h,constant.h,userdata.h,constrct.h,moduldef.h
dffctbsc.obj : scanner.h,pprint.h,constrnt.h,factbld.h,pattern.h,match.h
dffctbsc.obj : network.h,ruledef.h,cstrccom.h,agenda.h,reorder.h,factmngr.h
dffctbsc.obj : multifld.h,fuzzylv.h,dffnxfun.h,extnfunc.h,memalloc.h,router.h
dffctbsc.obj : prntutil.h,factrhs.h,cstrcpsr.h,dffctpsr.h,dffctdef.h,dffctbin.h
dffctbsc.obj : modulbin.h,cstrcbin.h,dffctcmp.h,dffctbsc.h
dffctcmp.obj : setup.h,conscomp.h,symblcmp.h,dffctdef.h,symbol.h,fuzzyval.h
dffctcmp.obj : tmpltdef.h,expressn.h,exprnops.h,evaluatn.h,constant.h,userdata.h
dffctcmp.obj : constrct.h,moduldef.h,scanner.h,pprint.h,constrnt.h,factbld.h
dffctcmp.obj : pattern.h,match.h,network.h,ruledef.h,cstrccom.h,agenda.h
dffctcmp.obj : reorder.h,factmngr.h,multifld.h,fuzzylv.h,dffnxfun.h,extnfunc.h
dffctcmp.obj : dffctcmp.h
dffctdef.obj : setup.h,memalloc.h,dffctpsr.h,dffctbsc.h,bload.h,exprnbin.h
dffctdef.obj : sysdep.h,symblbin.h,dffctbin.h,modulbin.h,cstrcbin.h,constrct.h
dffctdef.obj : moduldef.h,userdata.h,scanner.h,pprint.h,dffctcmp.h,dffctdef.h
dffctdef.obj : symbol.h,fuzzyval.h,tmpltdef.h,expressn.h,exprnops.h,evaluatn.h
dffctdef.obj : constant.h,constrnt.h,factbld.h,pattern.h,match.h,network.h
dffctdef.obj : ruledef.h,cstrccom.h,agenda.h,reorder.h,factmngr.h,multifld.h
dffctdef.obj : fuzzylv.h,dffnxfun.h,extnfunc.h
dffctpsr.obj : setup.h,memalloc.h,router.h,prntutil.h,cstrcpsr.h,evaluatn.h
dffctpsr.obj : constant.h,userdata.h,factrhs.h,bload.h,exprnbin.h,sysdep.h
dffctpsr.obj : symblbin.h,dffctdef.h,symbol.h,fuzzyval.h,tmpltdef.h,expressn.h
dffctpsr.obj : exprnops.h,constrct.h,moduldef.h,scanner.h,pprint.h,constrnt.h
dffctpsr.obj : factbld.h,pattern.h,match.h,network.h,ruledef.h,cstrccom.h
dffctpsr.obj : agenda.h,reorder.h,factmngr.h,multifld.h,fuzzylv.h,dffnxfun.h
dffctpsr.obj : extnfunc.h,dffctbsc.h,dffctpsr.h
dffnxbin.obj : setup.h,bload.h,exprnbin.h,sysdep.h,symblbin.h,bsave.h,memalloc.h
dffnxbin.obj : cstrcbin.h,constrct.h,moduldef.h,userdata.h,scanner.h,pprint.h
dffnxbin.obj : modulbin.h,dffnxbin.h,dffnxfun.h
dffnxcmp.obj : setup.h,conscomp.h,symblcmp.h,dffnxcmp.h,dffnxfun.h
dffnxexe.obj : setup.h,constrct.h,moduldef.h,userdata.h,scanner.h,pprint.h
dffnxexe.obj : prcdrfun.h,prccode.h,expressn.h,exprnops.h,evaluatn.h,constant.h
dffnxexe.obj : symbol.h,fuzzyval.h,tmpltdef.h,constrnt.h,factbld.h,pattern.h
dffnxexe.obj : match.h,network.h,ruledef.h,cstrccom.h,agenda.h,reorder.h
dffnxexe.obj : factmngr.h,multifld.h,fuzzylv.h,dffnxfun.h,extnfunc.h,proflfun.h
dffnxexe.obj : router.h,prntutil.h,utility.h,watch.h,dffnxexe.h
dffnxfun.obj : setup.h,bload.h,exprnbin.h,sysdep.h,symblbin.h,dffnxbin.h
dffnxfun.obj : dffnxfun.h,dffnxcmp.h,constrct.h,moduldef.h,userdata.h,scanner.h
dffnxfun.obj : pprint.h,cstrcpsr.h,evaluatn.h,constant.h,dffnxpsr.h,modulpsr.h
dffnxfun.obj : extnfunc.h,dffnxexe.h,watch.h,argacces.h,symbol.h,fuzzyval.h
dffnxfun.obj : tmpltdef.h,expressn.h,exprnops.h,constrnt.h,factbld.h,pattern.h
dffnxfun.obj : match.h,network.h,ruledef.h,cstrccom.h,agenda.h,reorder.h
dffnxfun.obj : factmngr.h,multifld.h,fuzzylv.h,memalloc.h,router.h,prntutil.h
dffnxpsr.obj : setup.h,bload.h,exprnbin.h,sysdep.h,symblbin.h,network.h
dffnxpsr.obj : ruledef.h,cstrccom.h,agenda.h,genrccom.h,constrct.h,moduldef.h
dffnxpsr.obj : userdata.h,scanner.h,pprint.h,evaluatn.h,constant.h,genrcfun.h
dffnxpsr.obj : object.h,constrnt.h,expressn.h,exprnops.h,multifld.h,symbol.h
dffnxpsr.obj : fuzzyval.h,tmpltdef.h,factbld.h,pattern.h,match.h,reorder.h
dffnxpsr.obj : factmngr.h,fuzzylv.h,dffnxfun.h,extnfunc.h,memalloc.h,cstrcpsr.h
dffnxpsr.obj : exprnpsr.h,prccode.h,router.h,prntutil.h,dffnxpsr.h
dfinsbin.obj : setup.h,bload.h,exprnbin.h,sysdep.h,symblbin.h,bsave.h,memalloc.h
dfinsbin.obj : cstrcbin.h,constrct.h,moduldef.h,userdata.h,scanner.h,pprint.h
dfinsbin.obj : defins.h,modulbin.h,dfinsbin.h
dfinscmp.obj : setup.h,conscomp.h,symblcmp.h,defins.h,dfinscmp.h
drive.obj : setup.h,constant.h,memalloc.h,reteutil.h,prntutil.h,router.h
drive.obj : agenda.h,retract.h,lgcldpnd.h,match.h,network.h,ruledef.h,cstrccom.h
drive.obj : pattern.h,reorder.h,incrrset.h,drive.h,expressn.h,exprnops.h
edbasic.obj : setup.h,ed.h,argacces.h,symbol.h,fuzzyval.h,tmpltdef.h,expressn.h
edbasic.obj : exprnops.h,evaluatn.h,constant.h,userdata.h,constrct.h,moduldef.h
edbasic.obj : scanner.h,pprint.h,constrnt.h,factbld.h,pattern.h,match.h
edbasic.obj : network.h,ruledef.h,cstrccom.h,agenda.h,reorder.h,factmngr.h
edbasic.obj : multifld.h,fuzzylv.h,dffnxfun.h,extnfunc.h,memalloc.h,router.h
edbasic.obj : prntutil.h
edmain.obj : setup.h,ed.h,argacces.h,symbol.h,fuzzyval.h,tmpltdef.h,expressn.h
edmain.obj : exprnops.h,evaluatn.h,constant.h,userdata.h,constrct.h,moduldef.h
edmain.obj : scanner.h,pprint.h,constrnt.h,factbld.h,pattern.h,match.h,network.h
edmain.obj : ruledef.h,cstrccom.h,agenda.h,reorder.h,factmngr.h,multifld.h
edmain.obj : fuzzylv.h,dffnxfun.h,extnfunc.h,memalloc.h,router.h,prntutil.h
edmain.obj : sysdep.h
edmisc.obj : setup.h,ed.h,argacces.h,symbol.h,fuzzyval.h,tmpltdef.h,expressn.h
edmisc.obj : exprnops.h,evaluatn.h,constant.h,userdata.h,constrct.h,moduldef.h
edmisc.obj : scanner.h,pprint.h,constrnt.h,factbld.h,pattern.h,match.h,network.h
edmisc.obj : ruledef.h,cstrccom.h,agenda.h,reorder.h,factmngr.h,multifld.h
edmisc.obj : fuzzylv.h,dffnxfun.h,extnfunc.h,memalloc.h,router.h,prntutil.h
edmisc.obj : cstrcpsr.h
edstruct.obj : setup.h,ed.h,argacces.h,symbol.h,fuzzyval.h,tmpltdef.h,expressn.h
edstruct.obj : exprnops.h,evaluatn.h,constant.h,userdata.h,constrct.h,moduldef.h
edstruct.obj : scanner.h,pprint.h,constrnt.h,factbld.h,pattern.h,match.h
edstruct.obj : network.h,ruledef.h,cstrccom.h,agenda.h,reorder.h,factmngr.h
edstruct.obj : multifld.h,fuzzylv.h,dffnxfun.h,extnfunc.h,memalloc.h,router.h
edstruct.obj : prntutil.h
edterm.obj : setup.h,ed.h,argacces.h,symbol.h,fuzzyval.h,tmpltdef.h,expressn.h
edterm.obj : exprnops.h,evaluatn.h,constant.h,userdata.h,constrct.h,moduldef.h
edterm.obj : scanner.h,pprint.h,constrnt.h,factbld.h,pattern.h,match.h,network.h
edterm.obj : ruledef.h,cstrccom.h,agenda.h,reorder.h,factmngr.h,multifld.h
edterm.obj : fuzzylv.h,dffnxfun.h,extnfunc.h,memalloc.h,router.h,prntutil.h
emathfun.obj : setup.h,argacces.h,symbol.h,fuzzyval.h,tmpltdef.h,expressn.h
emathfun.obj : exprnops.h,evaluatn.h,constant.h,userdata.h,constrct.h,moduldef.h
emathfun.obj : scanner.h,pprint.h,constrnt.h,factbld.h,pattern.h,match.h
emathfun.obj : network.h,ruledef.h,cstrccom.h,agenda.h,reorder.h,factmngr.h
emathfun.obj : multifld.h,fuzzylv.h,dffnxfun.h,extnfunc.h,router.h,prntutil.h
emathfun.obj : emathfun.h
engine.obj : setup.h,agenda.h,argacces.h,symbol.h,fuzzyval.h,tmpltdef.h
engine.obj : expressn.h,exprnops.h,evaluatn.h,constant.h,userdata.h,constrct.h
engine.obj : moduldef.h,scanner.h,pprint.h,constrnt.h,factbld.h,pattern.h
engine.obj : match.h,network.h,ruledef.h,cstrccom.h,reorder.h,factmngr.h
engine.obj : multifld.h,fuzzylv.h,dffnxfun.h,extnfunc.h,inscom.h,object.h
engine.obj : memalloc.h,modulutl.h,prccode.h,prcdrfun.h,proflfun.h,reteutil.h
engine.obj : retract.h,router.h,prntutil.h,ruledlt.h,sysdep.h,utility.h,watch.h
engine.obj : engine.h,cfdef.h,fuzzyutl.h
evaluatn.obj : setup.h,symbol.h,fuzzyval.h,tmpltdef.h,expressn.h,exprnops.h
evaluatn.obj : evaluatn.h,constant.h,userdata.h,constrct.h,moduldef.h,scanner.h
evaluatn.obj : pprint.h,constrnt.h,factbld.h,pattern.h,match.h,network.h
evaluatn.obj : ruledef.h,cstrccom.h,agenda.h,reorder.h,factmngr.h,multifld.h
evaluatn.obj : fuzzylv.h,dffnxfun.h,extnfunc.h,fuzzyrhs.h,fuzzymod.h,fuzzypsr.h
evaluatn.obj : commline.h,memalloc.h,router.h,prntutil.h,prcdrfun.h,exprnpsr.h
evaluatn.obj : utility.h,proflfun.h,sysdep.h,genrccom.h,genrcfun.h,object.h
expressn.obj : setup.h,memalloc.h,router.h,prntutil.h,extnfunc.h,userdata.h
expressn.obj : exprnops.h,evaluatn.h,constant.h,expressn.h
exprnbin.obj : setup.h,memalloc.h,dffctdef.h,symbol.h,fuzzyval.h,tmpltdef.h
exprnbin.obj : expressn.h,exprnops.h,evaluatn.h,constant.h,userdata.h,constrct.h
exprnbin.obj : moduldef.h,scanner.h,pprint.h,constrnt.h,factbld.h,pattern.h
exprnbin.obj : match.h,network.h,ruledef.h,cstrccom.h,agenda.h,reorder.h
exprnbin.obj : factmngr.h,multifld.h,fuzzylv.h,dffnxfun.h,extnfunc.h,bload.h
exprnbin.obj : exprnbin.h,sysdep.h,symblbin.h,bsave.h,genrcbin.h,genrcfun.h
exprnbin.obj : object.h,dffnxbin.h,tmpltbin.h,cstrcbin.h,modulbin.h,globlbin.h
exprnbin.obj : globldef.h,objbin.h,insfun.h,inscom.h
exprnops.obj : setup.h,memalloc.h,router.h,prntutil.h,extnfunc.h,userdata.h
exprnops.obj : cstrnchk.h,cstrnutl.h,cstrnops.h,exprnops.h
exprnpsr.obj : setup.h,constant.h,router.h,prntutil.h,strngrtr.h,scanner.h
exprnpsr.obj : pprint.h,memalloc.h,argacces.h,symbol.h,fuzzyval.h,tmpltdef.h
exprnpsr.obj : expressn.h,exprnops.h,evaluatn.h,userdata.h,constrct.h,moduldef.h
exprnpsr.obj : constrnt.h,factbld.h,pattern.h,match.h,network.h,ruledef.h
exprnpsr.obj : cstrccom.h,agenda.h,reorder.h,factmngr.h,multifld.h,fuzzylv.h
exprnpsr.obj : dffnxfun.h,extnfunc.h,cstrnchk.h,exprnpsr.h,modulutl.h,prcdrfun.h
exprnpsr.obj : genrccom.h,genrcfun.h,object.h
extnfunc.obj : setup.h,constant.h,router.h,prntutil.h,memalloc.h,evaluatn.h
extnfunc.obj : userdata.h,extnfunc.h
factbin.obj : setup.h,memalloc.h,tmpltdef.h,expressn.h,exprnops.h,evaluatn.h
factbin.obj : constant.h,userdata.h,constrct.h,moduldef.h,scanner.h,pprint.h
factbin.obj : constrnt.h,factbld.h,pattern.h,match.h,network.h,ruledef.h
factbin.obj : cstrccom.h,agenda.h,reorder.h,factmngr.h,multifld.h,fuzzylv.h
factbin.obj : dffnxfun.h,extnfunc.h,bload.h,exprnbin.h,sysdep.h,symblbin.h
factbin.obj : bsave.h,rulebin.h,modulbin.h,cstrcbin.h,factbin.h
factbld.obj : setup.h,memalloc.h,reteutil.h,router.h,prntutil.h,reorder.h
factbld.obj : factcmp.h,pattern.h,match.h,network.h,ruledef.h,cstrccom.h
factbld.obj : agenda.h,factmch.h,evaluatn.h,constant.h,userdata.h,factmngr.h
factbld.obj : multifld.h,factbld.h,factgen.h,factlhs.h,symbol.h,fuzzyval.h
factbld.obj : tmpltdef.h,expressn.h,exprnops.h,constrct.h,moduldef.h,scanner.h
factbld.obj : pprint.h,constrnt.h,fuzzylv.h,dffnxfun.h,extnfunc.h,argacces.h
factbld.obj : modulutl.h
factcmp.obj : setup.h,factbld.h,pattern.h,match.h,network.h,ruledef.h,cstrccom.h
factcmp.obj : agenda.h,reorder.h,conscomp.h,symblcmp.h,factcmp.h,tmpltdef.h
factcmp.obj : expressn.h,exprnops.h,evaluatn.h,constant.h,userdata.h,constrct.h
factcmp.obj : moduldef.h,scanner.h,pprint.h,constrnt.h,factmngr.h,multifld.h
factcmp.obj : fuzzylv.h,dffnxfun.h,extnfunc.h
factcom.obj : setup.h,memalloc.h,exprnpsr.h,factmngr.h,multifld.h,argacces.h
factcom.obj : symbol.h,fuzzyval.h,tmpltdef.h,expressn.h,exprnops.h,evaluatn.h
factcom.obj : constant.h,userdata.h,constrct.h,moduldef.h,scanner.h,pprint.h
factcom.obj : constrnt.h,factbld.h,pattern.h,match.h,network.h,ruledef.h
factcom.obj : cstrccom.h,agenda.h,reorder.h,fuzzylv.h,dffnxfun.h,extnfunc.h
factcom.obj : router.h,prntutil.h,factrhs.h,factmch.h,tmpltpsr.h,tmpltutl.h
factcom.obj : facthsh.h,modulutl.h,strngrtr.h,tmpltfun.h,cfdef.h,fuzzyutl.h
factcom.obj : bload.h,exprnbin.h,sysdep.h,symblbin.h,factcom.h
factfun.obj : setup.h,extnfunc.h,userdata.h,argacces.h,symbol.h,fuzzyval.h
factfun.obj : tmpltdef.h,expressn.h,exprnops.h,evaluatn.h,constant.h,constrct.h
factfun.obj : moduldef.h,scanner.h,pprint.h,constrnt.h,factbld.h,pattern.h
factfun.obj : match.h,network.h,ruledef.h,cstrccom.h,agenda.h,reorder.h
factfun.obj : factmngr.h,multifld.h,fuzzylv.h,dffnxfun.h,prntutil.h,tmpltutl.h
factfun.obj : factfun.h
factgen.obj : setup.h,constant.h,memalloc.h,router.h,prntutil.h,scanner.h
factgen.obj : pprint.h,exprnpsr.h,constrct.h,moduldef.h,userdata.h,network.h
factgen.obj : ruledef.h,cstrccom.h,agenda.h,reteutil.h,factmch.h,evaluatn.h
factgen.obj : factmngr.h,multifld.h,factbld.h,pattern.h,match.h,reorder.h
factgen.obj : factrete.h,factprt.h,tmpltdef.h,expressn.h,exprnops.h,constrnt.h
factgen.obj : fuzzylv.h,dffnxfun.h,extnfunc.h,tmpltlhs.h,symbol.h,fuzzyval.h
factgen.obj : factgen.h
facthsh.obj : setup.h,symbol.h,fuzzyval.h,tmpltdef.h,expressn.h,exprnops.h
facthsh.obj : evaluatn.h,constant.h,userdata.h,constrct.h,moduldef.h,scanner.h
facthsh.obj : pprint.h,constrnt.h,factbld.h,pattern.h,match.h,network.h
facthsh.obj : ruledef.h,cstrccom.h,agenda.h,reorder.h,factmngr.h,multifld.h
facthsh.obj : fuzzylv.h,dffnxfun.h,extnfunc.h,fuzzyutl.h,memalloc.h,router.h
facthsh.obj : prntutil.h,lgcldpnd.h,facthsh.h,cfdef.h
factlhs.obj : setup.h,router.h,prntutil.h,reorder.h,pattern.h,match.h,network.h
factlhs.obj : ruledef.h,cstrccom.h,agenda.h,tmpltpsr.h,tmpltdef.h,expressn.h
factlhs.obj : exprnops.h,evaluatn.h,constant.h,userdata.h,constrct.h,moduldef.h
factlhs.obj : scanner.h,pprint.h,constrnt.h,factbld.h,factmngr.h,multifld.h
factlhs.obj : fuzzylv.h,dffnxfun.h,extnfunc.h,tmpltlhs.h,symbol.h,fuzzyval.h
factlhs.obj : tmpltutl.h,modulutl.h,modulpsr.h,cstrcpsr.h,factlhs.h
factmch.obj : setup.h,memalloc.h,extnfunc.h,userdata.h,router.h,prntutil.h
factmch.obj : incrrset.h,reteutil.h,drive.h,expressn.h,exprnops.h,factgen.h
factmch.obj : factrete.h,tmpltdef.h,evaluatn.h,constant.h,constrct.h,moduldef.h
factmch.obj : scanner.h,pprint.h,constrnt.h,factbld.h,pattern.h,match.h
factmch.obj : network.h,ruledef.h,cstrccom.h,agenda.h,reorder.h,factmngr.h
factmch.obj : multifld.h,fuzzylv.h,dffnxfun.h,factmch.h
factmngr.obj : setup.h,constant.h,symbol.h,fuzzyval.h,tmpltdef.h,expressn.h
factmngr.obj : exprnops.h,evaluatn.h,userdata.h,constrct.h,moduldef.h,scanner.h
factmngr.obj : pprint.h,constrnt.h,factbld.h,pattern.h,match.h,network.h
factmngr.obj : ruledef.h,cstrccom.h,agenda.h,reorder.h,factmngr.h,multifld.h
factmngr.obj : fuzzylv.h,dffnxfun.h,extnfunc.h,memalloc.h,exprnpsr.h,argacces.h
factmngr.obj : router.h,prntutil.h,strngrtr.h,reteutil.h,retract.h,filecom.h
factmngr.obj : factfun.h,factrhs.h,factmch.h,watch.h,utility.h,factbin.h
factmngr.obj : facthsh.h,default.h,commline.h,engine.h,lgcldpnd.h,drive.h
factmngr.obj : ruledlt.h,tmpltbsc.h,tmpltutl.h,tmpltfun.h,fuzzyutl.h,cfdef.h
factprt.obj : setup.h,symbol.h,fuzzyval.h,tmpltdef.h,expressn.h,exprnops.h
factprt.obj : evaluatn.h,constant.h,userdata.h,constrct.h,moduldef.h,scanner.h
factprt.obj : pprint.h,constrnt.h,factbld.h,pattern.h,match.h,network.h
factprt.obj : ruledef.h,cstrccom.h,agenda.h,reorder.h,factmngr.h,multifld.h
factprt.obj : fuzzylv.h,dffnxfun.h,extnfunc.h,router.h,prntutil.h,factgen.h
factprt.obj : factprt.h
factrete.obj : setup.h,memalloc.h,extnfunc.h,userdata.h,router.h,prntutil.h
factrete.obj : incrrset.h,reteutil.h,drive.h,expressn.h,exprnops.h,factgen.h
factrete.obj : factmch.h,evaluatn.h,constant.h,factmngr.h,multifld.h,factbld.h
factrete.obj : pattern.h,match.h,network.h,ruledef.h,cstrccom.h,agenda.h
factrete.obj : reorder.h,factrete.h,fuzzyutl.h,fuzzyval.h,tmpltdef.h,constrct.h
factrete.obj : moduldef.h,scanner.h,pprint.h,constrnt.h,fuzzylv.h,dffnxfun.h
factrete.obj : fuzzydef.h,symbol.h
factrhs.obj : setup.h,constant.h,prntutil.h,extnfunc.h,userdata.h,pattern.h
factrhs.obj : match.h,network.h,ruledef.h,cstrccom.h,agenda.h,reorder.h
factrhs.obj : modulutl.h,modulpsr.h,cstrcpsr.h,evaluatn.h,bload.h,exprnbin.h
factrhs.obj : sysdep.h,symblbin.h,tmpltpsr.h,tmpltrhs.h,scanner.h,pprint.h
factrhs.obj : expressn.h,exprnops.h,tmpltdef.h,constrct.h,moduldef.h,constrnt.h
factrhs.obj : factbld.h,factmngr.h,multifld.h,fuzzylv.h,dffnxfun.h,tmpltutl.h
factrhs.obj : exprnpsr.h,strngrtr.h,router.h,factrhs.h,rulepsr.h,fuzzyrhs.h
factrhs.obj : fuzzymod.h,cfdef.h
filecom.obj : setup.h,memalloc.h,argacces.h,symbol.h,fuzzyval.h,tmpltdef.h
filecom.obj : expressn.h,exprnops.h,evaluatn.h,constant.h,userdata.h,constrct.h
filecom.obj : moduldef.h,scanner.h,pprint.h,constrnt.h,factbld.h,pattern.h
filecom.obj : match.h,network.h,ruledef.h,cstrccom.h,agenda.h,reorder.h
filecom.obj : factmngr.h,multifld.h,fuzzylv.h,dffnxfun.h,extnfunc.h,router.h
filecom.obj : prntutil.h,strngrtr.h,cstrcpsr.h,utility.h,commline.h,prcdrfun.h
filecom.obj : filecom.h,bsave.h,bload.h,exprnbin.h,sysdep.h,symblbin.h
filertr.obj : setup.h,constant.h,memalloc.h,router.h,prntutil.h,filertr.h
fuzzycom.obj : setup.h,extnfunc.h,userdata.h,evaluatn.h,constant.h,router.h
fuzzycom.obj : prntutil.h,argacces.h,symbol.h,fuzzyval.h,tmpltdef.h,expressn.h
fuzzycom.obj : exprnops.h,constrct.h,moduldef.h,scanner.h,pprint.h,constrnt.h
fuzzycom.obj : factbld.h,pattern.h,match.h,network.h,ruledef.h,cstrccom.h
fuzzycom.obj : agenda.h,reorder.h,factmngr.h,multifld.h,fuzzylv.h,dffnxfun.h
fuzzycom.obj : memalloc.h,factrhs.h,modulutl.h,fuzzycom.h,fuzzymod.h,fuzzydef.h
fuzzycom.obj : fuzzyrhs.h,fuzzyutl.h
fuzzydef.obj : setup.h,fuzzydef.h,fuzzycom.h,scanner.h,pprint.h,fuzzyval.h
fuzzydef.obj : tmpltdef.h,expressn.h,exprnops.h,evaluatn.h,constant.h,userdata.h
fuzzydef.obj : constrct.h,moduldef.h,constrnt.h,factbld.h,pattern.h,match.h
fuzzydef.obj : network.h,ruledef.h,cstrccom.h,agenda.h,reorder.h,factmngr.h
fuzzydef.obj : multifld.h,fuzzylv.h,dffnxfun.h,extnfunc.h,fuzzypsr.h,fuzzymod.h
fuzzylhs.obj : setup.h,tmpltdef.h,expressn.h,exprnops.h,evaluatn.h,constant.h
fuzzylhs.obj : userdata.h,constrct.h,moduldef.h,scanner.h,pprint.h,constrnt.h
fuzzylhs.obj : factbld.h,pattern.h,match.h,network.h,ruledef.h,cstrccom.h
fuzzylhs.obj : agenda.h,reorder.h,factmngr.h,multifld.h,fuzzylv.h,dffnxfun.h
fuzzylhs.obj : extnfunc.h,fuzzylhs.h,fuzzyrhs.h,fuzzymod.h
fuzzymod.obj : setup.h,fuzzyrhs.h,fuzzymod.h,fuzzyutl.h,fuzzypsr.h,memalloc.h
fuzzymod.obj : router.h,prntutil.h
fuzzypsr.obj : setup.h,extnfunc.h,userdata.h,prntutil.h,scanner.h,pprint.h
fuzzypsr.obj : constant.h,symbol.h,fuzzyval.h,tmpltdef.h,expressn.h,exprnops.h
fuzzypsr.obj : evaluatn.h,constrct.h,moduldef.h,constrnt.h,factbld.h,pattern.h
fuzzypsr.obj : match.h,network.h,ruledef.h,cstrccom.h,agenda.h,reorder.h
fuzzypsr.obj : factmngr.h,multifld.h,fuzzylv.h,dffnxfun.h,memalloc.h,modulutl.h
fuzzypsr.obj : fuzzypsr.h,fuzzyrhs.h,fuzzymod.h,fuzzyutl.h
fuzzyrhs.obj : setup.h,fuzzyrhs.h,fuzzymod.h,fuzzyval.h,tmpltdef.h,expressn.h
fuzzyrhs.obj : exprnops.h,evaluatn.h,constant.h,userdata.h,constrct.h,moduldef.h
fuzzyrhs.obj : scanner.h,pprint.h,constrnt.h,factbld.h,pattern.h,match.h
fuzzyrhs.obj : network.h,ruledef.h,cstrccom.h,agenda.h,reorder.h,factmngr.h
fuzzyrhs.obj : multifld.h,fuzzylv.h,dffnxfun.h,extnfunc.h,fuzzyutl.h,fuzzypsr.h
fuzzyrhs.obj : symbol.h,exprnpsr.h,memalloc.h,prntutil.h,router.h
fuzzyutl.obj : setup.h,symbol.h,fuzzyval.h,tmpltdef.h,expressn.h,exprnops.h
fuzzyutl.obj : evaluatn.h,constant.h,userdata.h,constrct.h,moduldef.h,scanner.h
fuzzyutl.obj : pprint.h,constrnt.h,factbld.h,pattern.h,match.h,network.h
fuzzyutl.obj : ruledef.h,cstrccom.h,agenda.h,reorder.h,factmngr.h,multifld.h
fuzzyutl.obj : fuzzylv.h,dffnxfun.h,extnfunc.h,fuzzydef.h,fuzzyutl.h,fuzzyrhs.h
fuzzyutl.obj : fuzzymod.h,fuzzypsr.h,reteutil.h,memalloc.h,engine.h,router.h
fuzzyutl.obj : prntutil.h,argacces.h,cfdef.h
generate.obj : setup.h,constant.h,memalloc.h,symbol.h,fuzzyval.h,tmpltdef.h
generate.obj : expressn.h,exprnops.h,evaluatn.h,userdata.h,constrct.h,moduldef.h
generate.obj : scanner.h,pprint.h,constrnt.h,factbld.h,pattern.h,match.h
generate.obj : network.h,ruledef.h,cstrccom.h,agenda.h,reorder.h,factmngr.h
generate.obj : multifld.h,fuzzylv.h,dffnxfun.h,extnfunc.h,exprnpsr.h,argacces.h
generate.obj : router.h,prntutil.h,generate.h,globlpsr.h
genrcbin.obj : setup.h,constant.h,memalloc.h,bload.h,exprnbin.h,sysdep.h
genrcbin.obj : symblbin.h,bsave.h,cstrcbin.h,constrct.h,moduldef.h,userdata.h
genrcbin.obj : scanner.h,pprint.h,objbin.h,genrccom.h,evaluatn.h,genrcfun.h
genrcbin.obj : object.h,constrnt.h,expressn.h,exprnops.h,multifld.h,symbol.h
genrcbin.obj : fuzzyval.h,tmpltdef.h,factbld.h,pattern.h,match.h,network.h
genrcbin.obj : ruledef.h,cstrccom.h,agenda.h,reorder.h,factmngr.h,fuzzylv.h
genrcbin.obj : dffnxfun.h,extnfunc.h,modulbin.h,genrcbin.h,router.h,prntutil.h
genrccmp.obj : setup.h,network.h,ruledef.h,cstrccom.h,agenda.h,genrccom.h
genrccmp.obj : constrct.h,moduldef.h,userdata.h,scanner.h,pprint.h,evaluatn.h
genrccmp.obj : constant.h,genrcfun.h,object.h,constrnt.h,expressn.h,exprnops.h
genrccmp.obj : multifld.h,symbol.h,fuzzyval.h,tmpltdef.h,factbld.h,pattern.h
genrccmp.obj : match.h,reorder.h,factmngr.h,fuzzylv.h,dffnxfun.h,extnfunc.h
genrccmp.obj : conscomp.h,symblcmp.h,objcmp.h,genrccmp.h
genrccom.obj : setup.h,network.h,ruledef.h,cstrccom.h,agenda.h,bload.h
genrccom.obj : exprnbin.h,sysdep.h,symblbin.h,genrcbin.h,genrcfun.h,object.h
genrccom.obj : constrct.h,moduldef.h,userdata.h,scanner.h,pprint.h,constrnt.h
genrccom.obj : expressn.h,exprnops.h,multifld.h,symbol.h,fuzzyval.h,tmpltdef.h
genrccom.obj : evaluatn.h,constant.h,factbld.h,pattern.h,match.h,reorder.h
genrccom.obj : factmngr.h,fuzzylv.h,dffnxfun.h,extnfunc.h,genrccmp.h,genrcpsr.h
genrccom.obj : classcom.h,inscom.h,watch.h,argacces.h,memalloc.h,cstrcpsr.h
genrccom.obj : genrcexe.h,modulpsr.h,router.h,prntutil.h,genrccom.h
genrcexe.obj : setup.h,classcom.h,classfun.h,object.h,constrct.h,moduldef.h
genrcexe.obj : userdata.h,scanner.h,pprint.h,constrnt.h,expressn.h,exprnops.h
genrcexe.obj : multifld.h,symbol.h,fuzzyval.h,tmpltdef.h,evaluatn.h,constant.h
genrcexe.obj : factbld.h,pattern.h,match.h,network.h,ruledef.h,cstrccom.h
genrcexe.obj : agenda.h,reorder.h,factmngr.h,fuzzylv.h,dffnxfun.h,extnfunc.h
genrcexe.obj : insfun.h,argacces.h,genrccom.h,genrcfun.h,prcdrfun.h,prccode.h
genrcexe.obj : proflfun.h,router.h,prntutil.h,utility.h,genrcexe.h
genrcfun.obj : setup.h,bload.h,exprnbin.h,sysdep.h,symblbin.h,classcom.h
genrcfun.obj : classfun.h,object.h,constrct.h,moduldef.h,userdata.h,scanner.h
genrcfun.obj : pprint.h,constrnt.h,expressn.h,exprnops.h,multifld.h,symbol.h
genrcfun.obj : fuzzyval.h,tmpltdef.h,evaluatn.h,constant.h,factbld.h,pattern.h
genrcfun.obj : match.h,network.h,ruledef.h,cstrccom.h,agenda.h,reorder.h
genrcfun.obj : factmngr.h,fuzzylv.h,dffnxfun.h,extnfunc.h,argacces.h,memalloc.h
genrcfun.obj : cstrcpsr.h,genrccom.h,genrcfun.h,genrcexe.h,prccode.h,router.h
genrcfun.obj : prntutil.h
genrcpsr.obj : setup.h,bload.h,exprnbin.h,sysdep.h,symblbin.h,dffnxfun.h
genrcpsr.obj : classfun.h,object.h,constrct.h,moduldef.h,userdata.h,scanner.h
genrcpsr.obj : pprint.h,constrnt.h,expressn.h,exprnops.h,multifld.h,symbol.h
genrcpsr.obj : fuzzyval.h,tmpltdef.h,evaluatn.h,constant.h,factbld.h,pattern.h
genrcpsr.obj : match.h,network.h,ruledef.h,cstrccom.h,agenda.h,reorder.h
genrcpsr.obj : factmngr.h,fuzzylv.h,extnfunc.h,classcom.h,memalloc.h,cstrcpsr.h
genrcpsr.obj : exprnpsr.h,genrccom.h,genrcfun.h,immthpsr.h,modulutl.h,prcdrpsr.h
genrcpsr.obj : prccode.h,router.h,prntutil.h,genrcpsr.h
globlbin.obj : setup.h,memalloc.h,multifld.h,globldef.h,bload.h,exprnbin.h
globlbin.obj : sysdep.h,symblbin.h,bsave.h,moduldef.h,globlbsc.h,evaluatn.h
globlbin.obj : constant.h,userdata.h,globlbin.h,modulbin.h,cstrcbin.h,constrct.h
globlbin.obj : scanner.h,pprint.h
globlbsc.obj : setup.h,constrct.h,moduldef.h,userdata.h,scanner.h,pprint.h
globlbsc.obj : extnfunc.h,watch.h,globlcom.h,globldef.h,globlbin.h,modulbin.h
globlbsc.obj : cstrcbin.h,globlcmp.h,globlbsc.h,evaluatn.h,constant.h
globlcmp.obj : setup.h,conscomp.h,symblcmp.h,globldef.h,globlcmp.h
globlcom.obj : setup.h,extnfunc.h,userdata.h,argacces.h,symbol.h,fuzzyval.h
globlcom.obj : tmpltdef.h,expressn.h,exprnops.h,evaluatn.h,constant.h,constrct.h
globlcom.obj : moduldef.h,scanner.h,pprint.h,constrnt.h,factbld.h,pattern.h
globlcom.obj : match.h,network.h,ruledef.h,cstrccom.h,agenda.h,reorder.h
globlcom.obj : factmngr.h,multifld.h,fuzzylv.h,dffnxfun.h,prntutil.h,router.h
globlcom.obj : globldef.h,globlcom.h
globldef.obj : setup.h,memalloc.h,modulpsr.h,multifld.h,router.h,prntutil.h
globldef.obj : strngrtr.h,modulutl.h,globlbsc.h,evaluatn.h,constant.h,userdata.h
globldef.obj : globlpsr.h,globlcom.h,utility.h,commline.h,bload.h,exprnbin.h
globldef.obj : sysdep.h,symblbin.h,globlbin.h,modulbin.h,cstrcbin.h,constrct.h
globldef.obj : moduldef.h,scanner.h,pprint.h,globldef.h,globlcmp.h
globlpsr.obj : setup.h,pprint.h,router.h,prntutil.h,memalloc.h,scanner.h
globlpsr.obj : evaluatn.h,constant.h,userdata.h,exprnpsr.h,constrct.h,moduldef.h
globlpsr.obj : multifld.h,watch.h,modulutl.h,modulpsr.h,cstrcpsr.h,globldef.h
globlpsr.obj : globlbsc.h,bload.h,exprnbin.h,sysdep.h,symblbin.h,globlpsr.h
immthpsr.obj : setup.h,classcom.h,classfun.h,object.h,constrct.h,moduldef.h
immthpsr.obj : userdata.h,scanner.h,pprint.h,constrnt.h,expressn.h,exprnops.h
immthpsr.obj : multifld.h,symbol.h,fuzzyval.h,tmpltdef.h,evaluatn.h,constant.h
immthpsr.obj : factbld.h,pattern.h,match.h,network.h,ruledef.h,cstrccom.h
immthpsr.obj : agenda.h,reorder.h,factmngr.h,fuzzylv.h,dffnxfun.h,extnfunc.h
immthpsr.obj : memalloc.h,cstrnutl.h,genrcpsr.h,genrcfun.h,prccode.h,immthpsr.h
incrrset.obj : setup.h,constant.h,agenda.h,router.h,prntutil.h,drive.h
incrrset.obj : expressn.h,exprnops.h,pattern.h,match.h,network.h,ruledef.h
incrrset.obj : cstrccom.h,reorder.h,evaluatn.h,userdata.h,argacces.h,symbol.h
incrrset.obj : fuzzyval.h,tmpltdef.h,constrct.h,moduldef.h,scanner.h,pprint.h
incrrset.obj : constrnt.h,factbld.h,factmngr.h,multifld.h,fuzzylv.h,dffnxfun.h
incrrset.obj : extnfunc.h,incrrset.h
inherpsr.obj : setup.h,classcom.h,classfun.h,object.h,constrct.h,moduldef.h
inherpsr.obj : userdata.h,scanner.h,pprint.h,constrnt.h,expressn.h,exprnops.h
inherpsr.obj : multifld.h,symbol.h,fuzzyval.h,tmpltdef.h,evaluatn.h,constant.h
inherpsr.obj : factbld.h,pattern.h,match.h,network.h,ruledef.h,cstrccom.h
inherpsr.obj : agenda.h,reorder.h,factmngr.h,fuzzylv.h,dffnxfun.h,extnfunc.h
inherpsr.obj : memalloc.h,modulutl.h,router.h,prntutil.h,inherpsr.h
inscom.obj : setup.h,argacces.h,symbol.h,fuzzyval.h,tmpltdef.h,expressn.h
inscom.obj : exprnops.h,evaluatn.h,constant.h,userdata.h,constrct.h,moduldef.h
inscom.obj : scanner.h,pprint.h,constrnt.h,factbld.h,pattern.h,match.h,network.h
inscom.obj : ruledef.h,cstrccom.h,agenda.h,reorder.h,factmngr.h,multifld.h
inscom.obj : fuzzylv.h,dffnxfun.h,extnfunc.h,classcom.h,classfun.h,object.h
inscom.obj : classinf.h,memalloc.h,exprnpsr.h,insfile.h,insfun.h,insmngr.h
inscom.obj : insmoddp.h,insmult.h,inspsr.h,msgfun.h,msgpass.h,router.h
inscom.obj : prntutil.h,strngrtr.h,utility.h,commline.h,inscom.h
insfile.obj : setup.h,argacces.h,symbol.h,fuzzyval.h,tmpltdef.h,expressn.h
insfile.obj : exprnops.h,evaluatn.h,constant.h,userdata.h,constrct.h,moduldef.h
insfile.obj : scanner.h,pprint.h,constrnt.h,factbld.h,pattern.h,match.h
insfile.obj : network.h,ruledef.h,cstrccom.h,agenda.h,reorder.h,factmngr.h
insfile.obj : multifld.h,fuzzylv.h,dffnxfun.h,extnfunc.h,classcom.h,classfun.h
insfile.obj : object.h,memalloc.h,inscom.h,insfun.h,insmngr.h,inspsr.h,router.h
insfile.obj : prntutil.h,strngrtr.h,symblbin.h,sysdep.h,insfile.h
insfun.obj : setup.h,argacces.h,symbol.h,fuzzyval.h,tmpltdef.h,expressn.h
insfun.obj : exprnops.h,evaluatn.h,constant.h,userdata.h,constrct.h,moduldef.h
insfun.obj : scanner.h,pprint.h,constrnt.h,factbld.h,pattern.h,match.h,network.h
insfun.obj : ruledef.h,cstrccom.h,agenda.h,reorder.h,factmngr.h,multifld.h
insfun.obj : fuzzylv.h,dffnxfun.h,extnfunc.h,classcom.h,classfun.h,object.h
insfun.obj : memalloc.h,cstrnchk.h,inscom.h,insmngr.h,modulutl.h,msgfun.h
insfun.obj : msgpass.h,prccode.h,router.h,prntutil.h,utility.h,drive.h
insfun.obj : objrtmch.h,insfun.h
insmngr.obj : setup.h,network.h,ruledef.h,cstrccom.h,agenda.h,drive.h,expressn.h
insmngr.obj : exprnops.h,objrtmch.h,lgcldpnd.h,match.h,pattern.h,reorder.h
insmngr.obj : classcom.h,classfun.h,object.h,constrct.h,moduldef.h,userdata.h
insmngr.obj : scanner.h,pprint.h,constrnt.h,multifld.h,symbol.h,fuzzyval.h
insmngr.obj : tmpltdef.h,evaluatn.h,constant.h,factbld.h,factmngr.h,fuzzylv.h
insmngr.obj : dffnxfun.h,extnfunc.h,memalloc.h,insfun.h,modulutl.h,msgfun.h
insmngr.obj : msgpass.h,prccode.h,router.h,prntutil.h,utility.h,insmngr.h
insmngr.obj : inscom.h
insmoddp.obj : setup.h,network.h,ruledef.h,cstrccom.h,agenda.h,objrtmch.h
insmoddp.obj : argacces.h,symbol.h,fuzzyval.h,tmpltdef.h,expressn.h,exprnops.h
insmoddp.obj : evaluatn.h,constant.h,userdata.h,constrct.h,moduldef.h,scanner.h
insmoddp.obj : pprint.h,constrnt.h,factbld.h,pattern.h,match.h,reorder.h
insmoddp.obj : factmngr.h,multifld.h,fuzzylv.h,dffnxfun.h,extnfunc.h,memalloc.h
insmoddp.obj : insfun.h,object.h,insmngr.h,inspsr.h,msgfun.h,msgpass.h,prccode.h
insmoddp.obj : router.h,prntutil.h,insmoddp.h
insmult.obj : setup.h,argacces.h,symbol.h,fuzzyval.h,tmpltdef.h,expressn.h
insmult.obj : exprnops.h,evaluatn.h,constant.h,userdata.h,constrct.h,moduldef.h
insmult.obj : scanner.h,pprint.h,constrnt.h,factbld.h,pattern.h,match.h
insmult.obj : network.h,ruledef.h,cstrccom.h,agenda.h,reorder.h,factmngr.h
insmult.obj : multifld.h,fuzzylv.h,dffnxfun.h,extnfunc.h,insfun.h,object.h
insmult.obj : msgfun.h,msgpass.h,multifun.h,router.h,prntutil.h,insmult.h
inspsr.obj : setup.h,classcom.h,classfun.h,object.h,constrct.h,moduldef.h
inspsr.obj : userdata.h,scanner.h,pprint.h,constrnt.h,expressn.h,exprnops.h
inspsr.obj : multifld.h,symbol.h,fuzzyval.h,tmpltdef.h,evaluatn.h,constant.h
inspsr.obj : factbld.h,pattern.h,match.h,network.h,ruledef.h,cstrccom.h,agenda.h
inspsr.obj : reorder.h,factmngr.h,fuzzylv.h,dffnxfun.h,extnfunc.h,classinf.h
inspsr.obj : exprnpsr.h,prntutil.h,router.h,inspsr.h
insquery.obj : setup.h,argacces.h,symbol.h,fuzzyval.h,tmpltdef.h,expressn.h
insquery.obj : exprnops.h,evaluatn.h,constant.h,userdata.h,constrct.h,moduldef.h
insquery.obj : scanner.h,pprint.h,constrnt.h,factbld.h,pattern.h,match.h
insquery.obj : network.h,ruledef.h,cstrccom.h,agenda.h,reorder.h,factmngr.h
insquery.obj : multifld.h,fuzzylv.h,dffnxfun.h,extnfunc.h,classcom.h,classfun.h
insquery.obj : object.h,memalloc.h,exprnpsr.h,insfun.h,insmngr.h,insqypsr.h
insquery.obj : prcdrfun.h,router.h,prntutil.h,utility.h,insquery.h
insqypsr.obj : setup.h,classcom.h,exprnpsr.h,extnfunc.h,userdata.h,insquery.h
insqypsr.obj : prcdrpsr.h,prntutil.h,router.h,scanner.h,pprint.h,strngrtr.h
insqypsr.obj : insqypsr.h
iofun.obj : setup.h,router.h,prntutil.h,strngrtr.h,filertr.h,argacces.h,symbol.h
iofun.obj : fuzzyval.h,tmpltdef.h,expressn.h,exprnops.h,evaluatn.h,constant.h
iofun.obj : userdata.h,constrct.h,moduldef.h,scanner.h,pprint.h,constrnt.h
iofun.obj : factbld.h,pattern.h,match.h,network.h,ruledef.h,cstrccom.h,agenda.h
iofun.obj : reorder.h,factmngr.h,multifld.h,fuzzylv.h,dffnxfun.h,extnfunc.h
iofun.obj : memalloc.h,commline.h,sysdep.h,utility.h,iofun.h
lgcldpnd.obj : setup.h,memalloc.h,router.h,prntutil.h,evaluatn.h,constant.h
lgcldpnd.obj : userdata.h,engine.h,reteutil.h,pattern.h,match.h,network.h
lgcldpnd.obj : ruledef.h,cstrccom.h,agenda.h,reorder.h,argacces.h,symbol.h
lgcldpnd.obj : fuzzyval.h,tmpltdef.h,expressn.h,exprnops.h,constrct.h,moduldef.h
lgcldpnd.obj : scanner.h,pprint.h,constrnt.h,factbld.h,factmngr.h,multifld.h
lgcldpnd.obj : fuzzylv.h,dffnxfun.h,extnfunc.h,insfun.h,object.h,lgcldpnd.h
main.obj : setup.h,sysdep.h,extnfunc.h,userdata.h,commline.h
memalloc.obj : setup.h,constant.h,memalloc.h,router.h,prntutil.h,utility.h
miscfun.obj : setup.h,memalloc.h,sysdep.h,multifld.h,exprnpsr.h,argacces.h
miscfun.obj : symbol.h,fuzzyval.h,tmpltdef.h,expressn.h,exprnops.h,evaluatn.h
miscfun.obj : constant.h,userdata.h,constrct.h,moduldef.h,scanner.h,pprint.h
miscfun.obj : constrnt.h,factbld.h,pattern.h,match.h,network.h,ruledef.h
miscfun.obj : cstrccom.h,agenda.h,reorder.h,factmngr.h,fuzzylv.h,dffnxfun.h
miscfun.obj : extnfunc.h,router.h,prntutil.h,utility.h,miscfun.h
modulbin.obj : setup.h,memalloc.h,constrct.h,moduldef.h,userdata.h,scanner.h
modulbin.obj : pprint.h,bload.h,exprnbin.h,sysdep.h,symblbin.h,bsave.h
modulbin.obj : modulbin.h
modulbsc.obj : setup.h,constrct.h,moduldef.h,userdata.h,scanner.h,pprint.h
modulbsc.obj : extnfunc.h,modulbin.h,prntutil.h,modulcmp.h,router.h,argacces.h
modulbsc.obj : symbol.h,fuzzyval.h,tmpltdef.h,expressn.h,exprnops.h,evaluatn.h
modulbsc.obj : constant.h,constrnt.h,factbld.h,pattern.h,match.h,network.h
modulbsc.obj : ruledef.h,cstrccom.h,agenda.h,reorder.h,factmngr.h,multifld.h
modulbsc.obj : fuzzylv.h,dffnxfun.h,bload.h,exprnbin.h,sysdep.h,symblbin.h
modulbsc.obj : modulbsc.h
modulcmp.obj : setup.h,conscomp.h,symblcmp.h,moduldef.h,modulcmp.h
moduldef.obj : setup.h,memalloc.h,constant.h,router.h,prntutil.h,extnfunc.h
moduldef.obj : userdata.h,argacces.h,symbol.h,fuzzyval.h,tmpltdef.h,expressn.h
moduldef.obj : exprnops.h,evaluatn.h,constrct.h,moduldef.h,scanner.h,pprint.h
moduldef.obj : constrnt.h,factbld.h,pattern.h,match.h,network.h,ruledef.h
moduldef.obj : cstrccom.h,agenda.h,reorder.h,factmngr.h,multifld.h,fuzzylv.h
moduldef.obj : dffnxfun.h,modulpsr.h,modulcmp.h,modulbsc.h,utility.h,bload.h
moduldef.obj : exprnbin.h,sysdep.h,symblbin.h,modulbin.h
modulpsr.obj : setup.h,memalloc.h,constant.h,router.h,prntutil.h,extnfunc.h
modulpsr.obj : userdata.h,argacces.h,symbol.h,fuzzyval.h,tmpltdef.h,expressn.h
modulpsr.obj : exprnops.h,evaluatn.h,constrct.h,moduldef.h,scanner.h,pprint.h
modulpsr.obj : constrnt.h,factbld.h,pattern.h,match.h,network.h,ruledef.h
modulpsr.obj : cstrccom.h,agenda.h,reorder.h,factmngr.h,multifld.h,fuzzylv.h
modulpsr.obj : dffnxfun.h,cstrcpsr.h,modulutl.h,utility.h,bload.h,exprnbin.h
modulpsr.obj : sysdep.h,symblbin.h,modulpsr.h
modulutl.obj : setup.h,memalloc.h,router.h,prntutil.h,modulpsr.h,modulutl.h
msgcom.obj : setup.h,argacces.h,symbol.h,fuzzyval.h,tmpltdef.h,expressn.h
msgcom.obj : exprnops.h,evaluatn.h,constant.h,userdata.h,constrct.h,moduldef.h
msgcom.obj : scanner.h,pprint.h,constrnt.h,factbld.h,pattern.h,match.h,network.h
msgcom.obj : ruledef.h,cstrccom.h,agenda.h,reorder.h,factmngr.h,multifld.h
msgcom.obj : fuzzylv.h,dffnxfun.h,extnfunc.h,classcom.h,classfun.h,object.h
msgcom.obj : classinf.h,insfun.h,insmoddp.h,msgfun.h,msgpass.h,prccode.h
msgcom.obj : router.h,prntutil.h,bload.h,exprnbin.h,sysdep.h,symblbin.h,msgpsr.h
msgcom.obj : watch.h,msgcom.h
msgfun.obj : setup.h,classcom.h,classfun.h,object.h,constrct.h,moduldef.h
msgfun.obj : userdata.h,scanner.h,pprint.h,constrnt.h,expressn.h,exprnops.h
msgfun.obj : multifld.h,symbol.h,fuzzyval.h,tmpltdef.h,evaluatn.h,constant.h
msgfun.obj : factbld.h,pattern.h,match.h,network.h,ruledef.h,cstrccom.h,agenda.h
msgfun.obj : reorder.h,factmngr.h,fuzzylv.h,dffnxfun.h,extnfunc.h,memalloc.h
msgfun.obj : insfun.h,prccode.h,router.h,prntutil.h,msgfun.h,msgpass.h
msgpass.obj : setup.h,argacces.h,symbol.h,fuzzyval.h,tmpltdef.h,expressn.h
msgpass.obj : exprnops.h,evaluatn.h,constant.h,userdata.h,constrct.h,moduldef.h
msgpass.obj : scanner.h,pprint.h,constrnt.h,factbld.h,pattern.h,match.h
msgpass.obj : network.h,ruledef.h,cstrccom.h,agenda.h,reorder.h,factmngr.h
msgpass.obj : multifld.h,fuzzylv.h,dffnxfun.h,extnfunc.h,classcom.h,classfun.h
msgpass.obj : object.h,memalloc.h,exprnpsr.h,insfun.h,msgfun.h,msgpass.h
msgpass.obj : prcdrfun.h,prccode.h,proflfun.h,router.h,prntutil.h,utility.h
msgpass.obj : commline.h,inscom.h
msgpsr.obj : setup.h,bload.h,exprnbin.h,sysdep.h,symblbin.h,classcom.h
msgpsr.obj : classfun.h,object.h,constrct.h,moduldef.h,userdata.h,scanner.h
msgpsr.obj : pprint.h,constrnt.h,expressn.h,exprnops.h,multifld.h,symbol.h
msgpsr.obj : fuzzyval.h,tmpltdef.h,evaluatn.h,constant.h,factbld.h,pattern.h
msgpsr.obj : match.h,network.h,ruledef.h,cstrccom.h,agenda.h,reorder.h
msgpsr.obj : factmngr.h,fuzzylv.h,dffnxfun.h,extnfunc.h,memalloc.h,cstrcpsr.h
msgpsr.obj : cstrnchk.h,exprnpsr.h,insfun.h,msgfun.h,msgpass.h,prccode.h
msgpsr.obj : router.h,prntutil.h,strngrtr.h,msgpsr.h
multifld.obj : setup.h,constant.h,memalloc.h,evaluatn.h,userdata.h,scanner.h
multifld.obj : pprint.h,router.h,prntutil.h,strngrtr.h,utility.h,multifld.h
multifld.obj : symbol.h,fuzzyval.h,tmpltdef.h,expressn.h,exprnops.h,constrct.h
multifld.obj : moduldef.h,constrnt.h,factbld.h,pattern.h,match.h,network.h
multifld.obj : ruledef.h,cstrccom.h,agenda.h,reorder.h,factmngr.h,fuzzylv.h
multifld.obj : dffnxfun.h,extnfunc.h,fuzzyutl.h,cfdef.h
multifun.obj : setup.h,memalloc.h,argacces.h,symbol.h,fuzzyval.h,tmpltdef.h
multifun.obj : expressn.h,exprnops.h,evaluatn.h,constant.h,userdata.h,constrct.h
multifun.obj : moduldef.h,scanner.h,pprint.h,constrnt.h,factbld.h,pattern.h
multifun.obj : match.h,network.h,ruledef.h,cstrccom.h,agenda.h,reorder.h
multifun.obj : factmngr.h,multifld.h,fuzzylv.h,dffnxfun.h,extnfunc.h,router.h
multifun.obj : prntutil.h,multifun.h,exprnpsr.h,prcdrpsr.h,prcdrfun.h,utility.h
multifun.obj : object.h
objbin.obj : setup.h,bload.h,exprnbin.h,sysdep.h,symblbin.h,bsave.h,classcom.h
objbin.obj : classfun.h,object.h,constrct.h,moduldef.h,userdata.h,scanner.h
objbin.obj : pprint.h,constrnt.h,expressn.h,exprnops.h,multifld.h,symbol.h
objbin.obj : fuzzyval.h,tmpltdef.h,evaluatn.h,constant.h,factbld.h,pattern.h
objbin.obj : match.h,network.h,ruledef.h,cstrccom.h,agenda.h,reorder.h
objbin.obj : factmngr.h,fuzzylv.h,dffnxfun.h,extnfunc.h,classini.h,memalloc.h
objbin.obj : cstrcbin.h,cstrnbin.h,insfun.h,modulbin.h,msgfun.h,msgpass.h
objbin.obj : prntutil.h,router.h,objbin.h
objcmp.obj : setup.h,conscomp.h,symblcmp.h,classcom.h,classfun.h,object.h
objcmp.obj : constrct.h,moduldef.h,userdata.h,scanner.h,pprint.h,constrnt.h
objcmp.obj : expressn.h,exprnops.h,multifld.h,symbol.h,fuzzyval.h,tmpltdef.h
objcmp.obj : evaluatn.h,constant.h,factbld.h,pattern.h,match.h,network.h
objcmp.obj : ruledef.h,cstrccom.h,agenda.h,reorder.h,factmngr.h,fuzzylv.h
objcmp.obj : dffnxfun.h,extnfunc.h,classini.h,cstrncmp.h,objcmp.h
objrtbin.obj : setup.h,bload.h,exprnbin.h,sysdep.h,symblbin.h,bsave.h,memalloc.h
objrtbin.obj : insfun.h,evaluatn.h,constant.h,userdata.h,moduldef.h,object.h
objrtbin.obj : constrct.h,scanner.h,pprint.h,constrnt.h,expressn.h,exprnops.h
objrtbin.obj : multifld.h,symbol.h,fuzzyval.h,tmpltdef.h,factbld.h,pattern.h
objrtbin.obj : match.h,network.h,ruledef.h,cstrccom.h,agenda.h,reorder.h
objrtbin.obj : factmngr.h,fuzzylv.h,dffnxfun.h,extnfunc.h,objrtmch.h,rulebin.h
objrtbin.obj : modulbin.h,cstrcbin.h,objrtbin.h
objrtbld.obj : setup.h,classcom.h,classfun.h,object.h,constrct.h,moduldef.h
objrtbld.obj : userdata.h,scanner.h,pprint.h,constrnt.h,expressn.h,exprnops.h
objrtbld.obj : multifld.h,symbol.h,fuzzyval.h,tmpltdef.h,evaluatn.h,constant.h
objrtbld.obj : factbld.h,pattern.h,match.h,network.h,ruledef.h,cstrccom.h
objrtbld.obj : agenda.h,reorder.h,factmngr.h,fuzzylv.h,dffnxfun.h,extnfunc.h
objrtbld.obj : memalloc.h,cstrnutl.h,cstrnchk.h,cstrnops.h,drive.h,exprnpsr.h
objrtbld.obj : insfun.h,insmngr.h,reteutil.h,rulepsr.h,utility.h,objrtmch.h
objrtbld.obj : objrtgen.h,objrtfnx.h,router.h,prntutil.h,objrtcmp.h,objrtbin.h
objrtbld.obj : objrtbld.h
objrtcmp.obj : setup.h,conscomp.h,symblcmp.h,objrtmch.h,pattern.h,match.h
objrtcmp.obj : network.h,ruledef.h,cstrccom.h,agenda.h,reorder.h,objrtcmp.h
objrtfnx.obj : setup.h,classcom.h,classfun.h,object.h,constrct.h,moduldef.h
objrtfnx.obj : userdata.h,scanner.h,pprint.h,constrnt.h,expressn.h,exprnops.h
objrtfnx.obj : multifld.h,symbol.h,fuzzyval.h,tmpltdef.h,evaluatn.h,constant.h
objrtfnx.obj : factbld.h,pattern.h,match.h,network.h,ruledef.h,cstrccom.h
objrtfnx.obj : agenda.h,reorder.h,factmngr.h,fuzzylv.h,dffnxfun.h,extnfunc.h
objrtfnx.obj : drive.h,objrtmch.h,reteutil.h,router.h,prntutil.h,objrtfnx.h
objrtgen.obj : setup.h,classfun.h,object.h,constrct.h,moduldef.h,userdata.h
objrtgen.obj : scanner.h,pprint.h,constrnt.h,expressn.h,exprnops.h,multifld.h
objrtgen.obj : symbol.h,fuzzyval.h,tmpltdef.h,evaluatn.h,constant.h,factbld.h
objrtgen.obj : pattern.h,match.h,network.h,ruledef.h,cstrccom.h,agenda.h
objrtgen.obj : reorder.h,factmngr.h,fuzzylv.h,dffnxfun.h,extnfunc.h,objrtfnx.h
objrtgen.obj : objrtgen.h
objrtmch.obj : setup.h,classfun.h,object.h,constrct.h,moduldef.h,userdata.h
objrtmch.obj : scanner.h,pprint.h,constrnt.h,expressn.h,exprnops.h,multifld.h
objrtmch.obj : symbol.h,fuzzyval.h,tmpltdef.h,evaluatn.h,constant.h,factbld.h
objrtmch.obj : pattern.h,match.h,network.h,ruledef.h,cstrccom.h,agenda.h
objrtmch.obj : reorder.h,factmngr.h,fuzzylv.h,dffnxfun.h,extnfunc.h,memalloc.h
objrtmch.obj : drive.h,lgcldpnd.h,incrrset.h,reteutil.h,ruledlt.h,retract.h
objrtmch.obj : router.h,prntutil.h,objrtfnx.h,objrtmch.h,insmngr.h
parsefun.obj : setup.h,argacces.h,symbol.h,fuzzyval.h,tmpltdef.h,expressn.h
parsefun.obj : exprnops.h,evaluatn.h,constant.h,userdata.h,constrct.h,moduldef.h
parsefun.obj : scanner.h,pprint.h,constrnt.h,factbld.h,pattern.h,match.h
parsefun.obj : network.h,ruledef.h,cstrccom.h,agenda.h,reorder.h,factmngr.h
parsefun.obj : multifld.h,fuzzylv.h,dffnxfun.h,extnfunc.h,cstrcpsr.h,exprnpsr.h
parsefun.obj : memalloc.h,prcdrpsr.h,router.h,prntutil.h,strngrtr.h,utility.h
parsefun.obj : parsefun.h
pattern.obj : setup.h,constant.h,memalloc.h,match.h,network.h,ruledef.h
pattern.obj : cstrccom.h,agenda.h,reteutil.h,constrnt.h,exprnpsr.h,router.h
pattern.obj : prntutil.h,cstrnchk.h,cstrnutl.h,rulecmp.h,conscomp.h,symblcmp.h
pattern.obj : extnfunc.h,userdata.h,pattern.h,reorder.h,tmpltdef.h,expressn.h
pattern.obj : exprnops.h,evaluatn.h,constrct.h,moduldef.h,scanner.h,pprint.h
pattern.obj : factbld.h,factmngr.h,multifld.h,fuzzylv.h,dffnxfun.h,tmpltlhs.h
pattern.obj : symbol.h,fuzzyval.h,fuzzylhs.h,fuzzypsr.h
pprint.obj : setup.h,constant.h,memalloc.h,utility.h,pprint.h
prccode.obj : setup.h,memalloc.h,constant.h,globlpsr.h,exprnpsr.h,multifld.h
prccode.obj : object.h,constrct.h,moduldef.h,userdata.h,scanner.h,pprint.h
prccode.obj : constrnt.h,expressn.h,exprnops.h,symbol.h,fuzzyval.h,tmpltdef.h
prccode.obj : evaluatn.h,factbld.h,pattern.h,match.h,network.h,ruledef.h
prccode.obj : cstrccom.h,agenda.h,reorder.h,factmngr.h,fuzzylv.h,dffnxfun.h
prccode.obj : extnfunc.h,prcdrpsr.h,router.h,prntutil.h,utility.h,prccode.h
prcdrfun.obj : setup.h,memalloc.h,router.h,prntutil.h,argacces.h,symbol.h
prcdrfun.obj : fuzzyval.h,tmpltdef.h,expressn.h,exprnops.h,evaluatn.h,constant.h
prcdrfun.obj : userdata.h,constrct.h,moduldef.h,scanner.h,pprint.h,constrnt.h
prcdrfun.obj : factbld.h,pattern.h,match.h,network.h,ruledef.h,cstrccom.h
prcdrfun.obj : agenda.h,reorder.h,factmngr.h,multifld.h,fuzzylv.h,dffnxfun.h
prcdrfun.obj : extnfunc.h,cstrnchk.h,cstrnops.h,exprnpsr.h,utility.h,prcdrpsr.h
prcdrfun.obj : prcdrfun.h,globldef.h
prcdrpsr.obj : setup.h,memalloc.h,router.h,prntutil.h,argacces.h,symbol.h
prcdrpsr.obj : fuzzyval.h,tmpltdef.h,expressn.h,exprnops.h,evaluatn.h,constant.h
prcdrpsr.obj : userdata.h,constrct.h,moduldef.h,scanner.h,pprint.h,constrnt.h
prcdrpsr.obj : factbld.h,pattern.h,match.h,network.h,ruledef.h,cstrccom.h
prcdrpsr.obj : agenda.h,reorder.h,factmngr.h,multifld.h,fuzzylv.h,dffnxfun.h
prcdrpsr.obj : extnfunc.h,cstrnchk.h,cstrnops.h,exprnpsr.h,utility.h,modulutl.h
prcdrpsr.obj : cstrnutl.h,prcdrpsr.h,globldef.h,globlpsr.h
prdctfun.obj : setup.h,exprnpsr.h,argacces.h,symbol.h,fuzzyval.h,tmpltdef.h
prdctfun.obj : expressn.h,exprnops.h,evaluatn.h,constant.h,userdata.h,constrct.h
prdctfun.obj : moduldef.h,scanner.h,pprint.h,constrnt.h,factbld.h,pattern.h
prdctfun.obj : match.h,network.h,ruledef.h,cstrccom.h,agenda.h,reorder.h
prdctfun.obj : factmngr.h,multifld.h,fuzzylv.h,dffnxfun.h,extnfunc.h,router.h
prdctfun.obj : prntutil.h,prdctfun.h
prntutil.obj : setup.h,constant.h,symbol.h,fuzzyval.h,tmpltdef.h,expressn.h
prntutil.obj : exprnops.h,evaluatn.h,userdata.h,constrct.h,moduldef.h,scanner.h
prntutil.obj : pprint.h,constrnt.h,factbld.h,pattern.h,match.h,network.h
prntutil.obj : ruledef.h,cstrccom.h,agenda.h,reorder.h,factmngr.h,multifld.h
prntutil.obj : fuzzylv.h,dffnxfun.h,extnfunc.h,utility.h,argacces.h,router.h
prntutil.obj : prntutil.h
proflfun.obj : setup.h,argacces.h,symbol.h,fuzzyval.h,tmpltdef.h,expressn.h
proflfun.obj : exprnops.h,evaluatn.h,constant.h,userdata.h,constrct.h,moduldef.h
proflfun.obj : scanner.h,pprint.h,constrnt.h,factbld.h,pattern.h,match.h
proflfun.obj : network.h,ruledef.h,cstrccom.h,agenda.h,reorder.h,factmngr.h
proflfun.obj : multifld.h,fuzzylv.h,dffnxfun.h,extnfunc.h,classcom.h,extobj.h
proflfun.obj : genrccom.h,genrcfun.h,object.h,memalloc.h,msgcom.h,router.h
proflfun.obj : prntutil.h,sysdep.h,proflfun.h
reorder.obj : setup.h,memalloc.h,tmpltdef.h,expressn.h,exprnops.h,evaluatn.h
reorder.obj : constant.h,userdata.h,constrct.h,moduldef.h,scanner.h,pprint.h
reorder.obj : constrnt.h,factbld.h,pattern.h,match.h,network.h,ruledef.h
reorder.obj : cstrccom.h,agenda.h,reorder.h,factmngr.h,multifld.h,fuzzylv.h
reorder.obj : dffnxfun.h,extnfunc.h,cstrnutl.h,rulelhs.h,prntutil.h,router.h
reteutil.obj : setup.h,memalloc.h,router.h,prntutil.h,retract.h,drive.h
reteutil.obj : expressn.h,exprnops.h,incrrset.h,pattern.h,match.h,network.h
reteutil.obj : ruledef.h,cstrccom.h,agenda.h,reorder.h,moduldef.h,reteutil.h
retract.obj : setup.h,constant.h,memalloc.h,symbol.h,fuzzyval.h,tmpltdef.h
retract.obj : expressn.h,exprnops.h,evaluatn.h,userdata.h,constrct.h,moduldef.h
retract.obj : scanner.h,pprint.h,constrnt.h,factbld.h,pattern.h,match.h
retract.obj : network.h,ruledef.h,cstrccom.h,agenda.h,reorder.h,factmngr.h
retract.obj : multifld.h,fuzzylv.h,dffnxfun.h,extnfunc.h,argacces.h,router.h
retract.obj : prntutil.h,drive.h,lgcldpnd.h,retract.h
router.obj : setup.h,constant.h,memalloc.h,filertr.h,strngrtr.h,extnfunc.h
router.obj : userdata.h,argacces.h,symbol.h,fuzzyval.h,tmpltdef.h,expressn.h
router.obj : exprnops.h,evaluatn.h,constrct.h,moduldef.h,scanner.h,pprint.h
router.obj : constrnt.h,factbld.h,pattern.h,match.h,network.h,ruledef.h
router.obj : cstrccom.h,agenda.h,reorder.h,factmngr.h,multifld.h,fuzzylv.h
router.obj : dffnxfun.h,sysdep.h,router.h,prntutil.h
rulebin.obj : setup.h,memalloc.h,bload.h,exprnbin.h,sysdep.h,symblbin.h,bsave.h
rulebin.obj : reteutil.h,agenda.h,engine.h,rulebsc.h,pattern.h,match.h,network.h
rulebin.obj : ruledef.h,cstrccom.h,reorder.h,moduldef.h,rulebin.h,modulbin.h
rulebin.obj : cstrcbin.h,constrct.h,userdata.h,scanner.h,pprint.h
rulebld.obj : setup.h,constant.h,memalloc.h,router.h,prntutil.h,watch.h
rulebld.obj : constrct.h,moduldef.h,userdata.h,scanner.h,pprint.h,drive.h
rulebld.obj : expressn.h,exprnops.h,pattern.h,match.h,network.h,ruledef.h
rulebld.obj : cstrccom.h,agenda.h,reorder.h,reteutil.h,incrrset.h,rulebld.h
rulebsc.obj : setup.h,argacces.h,symbol.h,fuzzyval.h,tmpltdef.h,expressn.h
rulebsc.obj : exprnops.h,evaluatn.h,constant.h,userdata.h,constrct.h,moduldef.h
rulebsc.obj : scanner.h,pprint.h,constrnt.h,factbld.h,pattern.h,match.h
rulebsc.obj : network.h,ruledef.h,cstrccom.h,agenda.h,reorder.h,factmngr.h
rulebsc.obj : multifld.h,fuzzylv.h,dffnxfun.h,extnfunc.h,router.h,prntutil.h
rulebsc.obj : watch.h,engine.h,rulebin.h,modulbin.h,cstrcbin.h,rulecmp.h
rulebsc.obj : conscomp.h,symblcmp.h,rulebsc.h
rulecmp.obj : setup.h,factbld.h,pattern.h,match.h,network.h,ruledef.h,cstrccom.h
rulecmp.obj : agenda.h,reorder.h,reteutil.h,rulecmp.h,conscomp.h,symblcmp.h
rulecmp.obj : extnfunc.h,userdata.h,fuzzyval.h,tmpltdef.h,expressn.h,exprnops.h
rulecmp.obj : evaluatn.h,constant.h,constrct.h,moduldef.h,scanner.h,pprint.h
rulecmp.obj : constrnt.h,factmngr.h,multifld.h,fuzzylv.h,dffnxfun.h,prntutil.h
rulecom.obj : setup.h,constant.h,memalloc.h,evaluatn.h,userdata.h,extnfunc.h
rulecom.obj : engine.h,watch.h,crstrtgy.h,agenda.h,symbol.h,fuzzyval.h
rulecom.obj : tmpltdef.h,expressn.h,exprnops.h,constrct.h,moduldef.h,scanner.h
rulecom.obj : pprint.h,constrnt.h,factbld.h,pattern.h,match.h,network.h
rulecom.obj : ruledef.h,cstrccom.h,reorder.h,factmngr.h,multifld.h,fuzzylv.h
rulecom.obj : dffnxfun.h,argacces.h,router.h,prntutil.h,reteutil.h,ruledlt.h
rulecom.obj : rulebin.h,modulbin.h,cstrcbin.h,lgcldpnd.h,incrrset.h,rulecom.h
rulecstr.obj : setup.h,router.h,prntutil.h,reorder.h,cstrnchk.h,cstrnops.h
rulecstr.obj : extnfunc.h,userdata.h,analysis.h,prcdrpsr.h,cstrnutl.h,rulepsr.h
rulecstr.obj : rulecstr.h
ruledef.obj : setup.h,memalloc.h,engine.h,pattern.h,match.h,network.h,ruledef.h
ruledef.obj : cstrccom.h,agenda.h,reorder.h,rulebsc.h,rulecom.h,drive.h
ruledef.obj : expressn.h,exprnops.h,rulepsr.h,ruledlt.h,bload.h,exprnbin.h
ruledef.obj : sysdep.h,symblbin.h,rulebin.h,modulbin.h,cstrcbin.h,constrct.h
ruledef.obj : moduldef.h,userdata.h,scanner.h,pprint.h,rulecmp.h,conscomp.h
ruledef.obj : symblcmp.h,extnfunc.h
ruledlt.obj : setup.h,memalloc.h,engine.h,reteutil.h,pattern.h,match.h,network.h
ruledlt.obj : ruledef.h,cstrccom.h,agenda.h,reorder.h,drive.h,expressn.h
ruledlt.obj : exprnops.h,retract.h,constrct.h,moduldef.h,userdata.h,scanner.h
ruledlt.obj : pprint.h,bload.h,exprnbin.h,sysdep.h,symblbin.h,ruledlt.h,symbol.h
ruledlt.obj : fuzzyval.h,tmpltdef.h,evaluatn.h,constant.h,constrnt.h,factbld.h
ruledlt.obj : factmngr.h,multifld.h,fuzzylv.h,dffnxfun.h,extnfunc.h
rulelhs.obj : setup.h,constant.h,symbol.h,fuzzyval.h,tmpltdef.h,expressn.h
rulelhs.obj : exprnops.h,evaluatn.h,userdata.h,constrct.h,moduldef.h,scanner.h
rulelhs.obj : pprint.h,constrnt.h,factbld.h,pattern.h,match.h,network.h
rulelhs.obj : ruledef.h,cstrccom.h,agenda.h,reorder.h,factmngr.h,multifld.h
rulelhs.obj : fuzzylv.h,dffnxfun.h,extnfunc.h,memalloc.h,exprnpsr.h,argacces.h
rulelhs.obj : router.h,prntutil.h,cstrnchk.h,rulelhs.h,cfdef.h
rulepsr.obj : setup.h,constant.h,memalloc.h,symbol.h,fuzzyval.h,tmpltdef.h
rulepsr.obj : expressn.h,exprnops.h,evaluatn.h,userdata.h,constrct.h,moduldef.h
rulepsr.obj : scanner.h,pprint.h,constrnt.h,factbld.h,pattern.h,match.h
rulepsr.obj : network.h,ruledef.h,cstrccom.h,agenda.h,reorder.h,factmngr.h
rulepsr.obj : multifld.h,fuzzylv.h,dffnxfun.h,extnfunc.h,router.h,prntutil.h
rulepsr.obj : engine.h,rulelhs.h,rulebld.h,cstrnchk.h,cstrnops.h,exprnpsr.h
rulepsr.obj : analysis.h,prcdrpsr.h,prccode.h,incrrset.h,rulecstr.h,watch.h
rulepsr.obj : ruledlt.h,cstrcpsr.h,rulebsc.h,lgcldpnd.h,tmpltfun.h,bload.h
rulepsr.obj : exprnbin.h,sysdep.h,symblbin.h,rulepsr.h
scanner.obj : setup.h,constant.h,router.h,prntutil.h,symbol.h,fuzzyval.h
scanner.obj : tmpltdef.h,expressn.h,exprnops.h,evaluatn.h,userdata.h,constrct.h
scanner.obj : moduldef.h,scanner.h,pprint.h,constrnt.h,factbld.h,pattern.h
scanner.obj : match.h,network.h,ruledef.h,cstrccom.h,agenda.h,reorder.h
scanner.obj : factmngr.h,multifld.h,fuzzylv.h,dffnxfun.h,extnfunc.h,utility.h
scanner.obj : memalloc.h
sortfun.obj : setup.h,argacces.h,symbol.h,fuzzyval.h,tmpltdef.h,expressn.h
sortfun.obj : exprnops.h,evaluatn.h,constant.h,userdata.h,constrct.h,moduldef.h
sortfun.obj : scanner.h,pprint.h,constrnt.h,factbld.h,pattern.h,match.h
sortfun.obj : network.h,ruledef.h,cstrccom.h,agenda.h,reorder.h,factmngr.h
sortfun.obj : multifld.h,fuzzylv.h,dffnxfun.h,extnfunc.h,memalloc.h,sysdep.h
sortfun.obj : sortfun.h
strngfun.obj : setup.h,memalloc.h,extnfunc.h,userdata.h,argacces.h,symbol.h
strngfun.obj : fuzzyval.h,tmpltdef.h,expressn.h,exprnops.h,evaluatn.h,constant.h
strngfun.obj : constrct.h,moduldef.h,scanner.h,pprint.h,constrnt.h,factbld.h
strngfun.obj : pattern.h,match.h,network.h,ruledef.h,cstrccom.h,agenda.h
strngfun.obj : reorder.h,factmngr.h,multifld.h,fuzzylv.h,dffnxfun.h,router.h
strngfun.obj : prntutil.h,strngrtr.h,prcdrpsr.h,cstrcpsr.h,exprnpsr.h,drive.h
strngfun.obj : strngfun.h
strngrtr.obj : setup.h,constant.h,memalloc.h,router.h,prntutil.h,strngrtr.h
symblbin.obj : setup.h,symbol.h,fuzzyval.h,tmpltdef.h,expressn.h,exprnops.h
symblbin.obj : evaluatn.h,constant.h,userdata.h,constrct.h,moduldef.h,scanner.h
symblbin.obj : pprint.h,constrnt.h,factbld.h,pattern.h,match.h,network.h
symblbin.obj : ruledef.h,cstrccom.h,agenda.h,reorder.h,factmngr.h,multifld.h
symblbin.obj : fuzzylv.h,dffnxfun.h,extnfunc.h,tmpltbin.h,cstrcbin.h,modulbin.h
symblbin.obj : fuzzyrhs.h,fuzzymod.h,fuzzypsr.h,memalloc.h,exprnpsr.h,argacces.h
symblbin.obj : router.h,prntutil.h,cstrnbin.h,bload.h,exprnbin.h,sysdep.h
symblbin.obj : symblbin.h,bsave.h
symblcmp.obj : setup.h,symbol.h,fuzzyval.h,tmpltdef.h,expressn.h,exprnops.h
symblcmp.obj : evaluatn.h,constant.h,userdata.h,constrct.h,moduldef.h,scanner.h
symblcmp.obj : pprint.h,constrnt.h,factbld.h,pattern.h,match.h,network.h
symblcmp.obj : ruledef.h,cstrccom.h,agenda.h,reorder.h,factmngr.h,multifld.h
symblcmp.obj : fuzzylv.h,dffnxfun.h,extnfunc.h,memalloc.h,exprnpsr.h,argacces.h
symblcmp.obj : cstrncmp.h,router.h,prntutil.h,conscomp.h,symblcmp.h,utility.h
symblcmp.obj : tmpltcmp.h
symbol.obj : setup.h,symbol.h,fuzzyval.h,tmpltdef.h,expressn.h,exprnops.h
symbol.obj : evaluatn.h,constant.h,userdata.h,constrct.h,moduldef.h,scanner.h
symbol.obj : pprint.h,constrnt.h,factbld.h,pattern.h,match.h,network.h,ruledef.h
symbol.obj : cstrccom.h,agenda.h,reorder.h,factmngr.h,multifld.h,fuzzylv.h
symbol.obj : dffnxfun.h,extnfunc.h,fuzzypsr.h,fuzzyrhs.h,fuzzymod.h,memalloc.h
symbol.obj : router.h,prntutil.h,utility.h,argacces.h
sysdep.obj : setup.h,argacces.h,symbol.h,fuzzyval.h,tmpltdef.h,expressn.h
sysdep.obj : exprnops.h,evaluatn.h,constant.h,userdata.h,constrct.h,moduldef.h
sysdep.obj : scanner.h,pprint.h,constrnt.h,factbld.h,pattern.h,match.h,network.h
sysdep.obj : ruledef.h,cstrccom.h,agenda.h,reorder.h,factmngr.h,multifld.h
sysdep.obj : fuzzylv.h,dffnxfun.h,extnfunc.h,bmathfun.h,conscomp.h,symblcmp.h
sysdep.obj : cstrcpsr.h,emathfun.h,filecom.h,iofun.h,memalloc.h,miscfun.h
sysdep.obj : multifun.h,parsefun.h,prccode.h,prdctfun.h,proflfun.h,prcdrfun.h
sysdep.obj : router.h,prntutil.h,sortfun.h,strngfun.h,textpro.h,utility.h
sysdep.obj : watch.h,sysdep.h,dffctdef.h,genrccom.h,genrcfun.h,object.h
sysdep.obj : globldef.h,cfdef.h,fuzzydef.h,extobj.h,developr.h
textpro.obj : setup.h,commline.h,memalloc.h,argacces.h,symbol.h,fuzzyval.h
textpro.obj : tmpltdef.h,expressn.h,exprnops.h,evaluatn.h,constant.h,userdata.h
textpro.obj : constrct.h,moduldef.h,scanner.h,pprint.h,constrnt.h,factbld.h
textpro.obj : pattern.h,match.h,network.h,ruledef.h,cstrccom.h,agenda.h
textpro.obj : reorder.h,factmngr.h,multifld.h,fuzzylv.h,dffnxfun.h,extnfunc.h
textpro.obj : router.h,prntutil.h,textpro.h
tmpltbin.obj : setup.h,memalloc.h,bload.h,exprnbin.h,sysdep.h,symblbin.h,bsave.h
tmpltbin.obj : factbin.h,factbld.h,pattern.h,match.h,network.h,ruledef.h
tmpltbin.obj : cstrccom.h,agenda.h,reorder.h,cstrnbin.h,factmngr.h,multifld.h
tmpltbin.obj : tmpltpsr.h,tmpltdef.h,expressn.h,exprnops.h,evaluatn.h,constant.h
tmpltbin.obj : userdata.h,constrct.h,moduldef.h,scanner.h,pprint.h,constrnt.h
tmpltbin.obj : fuzzylv.h,dffnxfun.h,extnfunc.h,tmpltutl.h,tmpltbin.h,cstrcbin.h
tmpltbin.obj : modulbin.h,fuzzyval.h,dffnxbin.h
tmpltbsc.obj : setup.h,argacces.h,symbol.h,fuzzyval.h,tmpltdef.h,expressn.h
tmpltbsc.obj : exprnops.h,evaluatn.h,constant.h,userdata.h,constrct.h,moduldef.h
tmpltbsc.obj : scanner.h,pprint.h,constrnt.h,factbld.h,pattern.h,match.h
tmpltbsc.obj : network.h,ruledef.h,cstrccom.h,agenda.h,reorder.h,factmngr.h
tmpltbsc.obj : multifld.h,fuzzylv.h,dffnxfun.h,extnfunc.h,memalloc.h,router.h
tmpltbsc.obj : prntutil.h,factrhs.h,cstrcpsr.h,tmpltpsr.h,tmpltbin.h,cstrcbin.h
tmpltbsc.obj : modulbin.h,tmpltcmp.h,tmpltutl.h,tmpltbsc.h
tmpltcmp.obj : setup.h,conscomp.h,symblcmp.h,factcmp.h,pattern.h,match.h
tmpltcmp.obj : network.h,ruledef.h,cstrccom.h,agenda.h,reorder.h,cstrncmp.h
tmpltcmp.obj : tmpltdef.h,expressn.h,exprnops.h,evaluatn.h,constant.h,userdata.h
tmpltcmp.obj : constrct.h,moduldef.h,scanner.h,pprint.h,constrnt.h,factbld.h
tmpltcmp.obj : factmngr.h,multifld.h,fuzzylv.h,dffnxfun.h,extnfunc.h,tmpltcmp.h
tmpltcmp.obj : fuzzyval.h,dffnxcmp.h,prntutil.h
tmpltdef.obj : setup.h,memalloc.h,exprnops.h,cstrccom.h,network.h,ruledef.h
tmpltdef.obj : agenda.h,tmpltpsr.h,tmpltbsc.h,tmpltutl.h,tmpltfun.h,router.h
tmpltdef.obj : prntutil.h,modulpsr.h,modulutl.h,cstrnchk.h,bload.h,exprnbin.h
tmpltdef.obj : sysdep.h,symblbin.h,tmpltbin.h,cstrcbin.h,constrct.h,moduldef.h
tmpltdef.obj : userdata.h,scanner.h,pprint.h,modulbin.h,tmpltcmp.h,tmpltdef.h
tmpltdef.obj : expressn.h,evaluatn.h,constant.h,constrnt.h,factbld.h,pattern.h
tmpltdef.obj : match.h,reorder.h,factmngr.h,multifld.h,fuzzylv.h,dffnxfun.h
tmpltdef.obj : extnfunc.h,fuzzypsr.h,fuzzyutl.h,symbol.h,fuzzyval.h
tmpltfun.obj : setup.h,constant.h,memalloc.h,symbol.h,fuzzyval.h,tmpltdef.h
tmpltfun.obj : expressn.h,exprnops.h,evaluatn.h,userdata.h,constrct.h,moduldef.h
tmpltfun.obj : scanner.h,pprint.h,constrnt.h,factbld.h,pattern.h,match.h
tmpltfun.obj : network.h,ruledef.h,cstrccom.h,agenda.h,reorder.h,factmngr.h
tmpltfun.obj : multifld.h,fuzzylv.h,dffnxfun.h,extnfunc.h,exprnpsr.h,argacces.h
tmpltfun.obj : router.h,prntutil.h,cstrnchk.h,default.h,commline.h,factrhs.h
tmpltfun.obj : modulutl.h,tmpltlhs.h,tmpltutl.h,tmpltrhs.h,tmpltfun.h
tmpltlhs.obj : setup.h,constant.h,memalloc.h,symbol.h,fuzzyval.h,tmpltdef.h
tmpltlhs.obj : expressn.h,exprnops.h,evaluatn.h,userdata.h,constrct.h,moduldef.h
tmpltlhs.obj : scanner.h,pprint.h,constrnt.h,factbld.h,pattern.h,match.h
tmpltlhs.obj : network.h,ruledef.h,cstrccom.h,agenda.h,reorder.h,factmngr.h
tmpltlhs.obj : multifld.h,fuzzylv.h,dffnxfun.h,extnfunc.h,exprnpsr.h,router.h
tmpltlhs.obj : prntutil.h,factrhs.h,modulutl.h,tmpltutl.h,tmpltlhs.h,fuzzylhs.h
tmpltlhs.obj : fuzzypsr.h
tmpltpsr.obj : setup.h,constant.h,memalloc.h,symbol.h,fuzzyval.h,tmpltdef.h
tmpltpsr.obj : expressn.h,exprnops.h,evaluatn.h,userdata.h,constrct.h,moduldef.h
tmpltpsr.obj : scanner.h,pprint.h,constrnt.h,factbld.h,pattern.h,match.h
tmpltpsr.obj : network.h,ruledef.h,cstrccom.h,agenda.h,reorder.h,factmngr.h
tmpltpsr.obj : multifld.h,fuzzylv.h,dffnxfun.h,extnfunc.h,exprnpsr.h,router.h
tmpltpsr.obj : prntutil.h,cstrnchk.h,cstrnpsr.h,cstrcpsr.h,bload.h,exprnbin.h
tmpltpsr.obj : sysdep.h,symblbin.h,default.h,watch.h,cstrnutl.h,tmpltbsc.h
tmpltpsr.obj : tmpltpsr.h,fuzzypsr.h
tmpltrhs.obj : setup.h,memalloc.h,prntutil.h,router.h,tmpltfun.h,tmpltdef.h
tmpltrhs.obj : expressn.h,exprnops.h,evaluatn.h,constant.h,userdata.h,constrct.h
tmpltrhs.obj : moduldef.h,scanner.h,pprint.h,constrnt.h,factbld.h,pattern.h
tmpltrhs.obj : match.h,network.h,ruledef.h,cstrccom.h,agenda.h,reorder.h
tmpltrhs.obj : factmngr.h,multifld.h,fuzzylv.h,dffnxfun.h,extnfunc.h,factrhs.h
tmpltrhs.obj : modulutl.h,default.h,tmpltutl.h,tmpltlhs.h,symbol.h,fuzzyval.h
tmpltrhs.obj : tmpltrhs.h,fuzzyrhs.h,fuzzymod.h
tmpltutl.obj : setup.h,extnfunc.h,userdata.h,memalloc.h,constrct.h,moduldef.h
tmpltutl.obj : scanner.h,pprint.h,router.h,prntutil.h,argacces.h,symbol.h
tmpltutl.obj : fuzzyval.h,tmpltdef.h,expressn.h,exprnops.h,evaluatn.h,constant.h
tmpltutl.obj : constrnt.h,factbld.h,pattern.h,match.h,network.h,ruledef.h
tmpltutl.obj : cstrccom.h,agenda.h,reorder.h,factmngr.h,multifld.h,fuzzylv.h
tmpltutl.obj : dffnxfun.h,cstrnchk.h,tmpltfun.h,tmpltpsr.h,modulutl.h,watch.h
tmpltutl.obj : tmpltbsc.h,tmpltutl.h,fuzzypsr.h,fuzzyutl.h,cfdef.h
userdata.obj : setup.h,userdata.h
utility.obj : setup.h,evaluatn.h,constant.h,userdata.h,facthsh.h,memalloc.h
utility.obj : multifld.h,prntutil.h,utility.h
watch.obj : setup.h,constant.h,memalloc.h,router.h,prntutil.h,argacces.h
watch.obj : symbol.h,fuzzyval.h,tmpltdef.h,expressn.h,exprnops.h,evaluatn.h
watch.obj : userdata.h,constrct.h,moduldef.h,scanner.h,pprint.h,constrnt.h
watch.obj : factbld.h,pattern.h,match.h,network.h,ruledef.h,cstrccom.h,agenda.h
watch.obj : reorder.h,factmngr.h,multifld.h,fuzzylv.h,dffnxfun.h,extnfunc.h
watch.obj : watch.h
